### ISSUE TITLE
psf.pars not returning list of parameters

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#1109]
I know that the PSF stuff is a little bit different than other model components (eg `gauss2d`) but shouldn't the `.pars` return the list of parameters?

```python
sherpa In [1]: load_data("fi/out_broad_thresh.img")

sherpa In [2]: load_psf("mypsf", "tmpjrv7xb58_simulate_p.psf")

sherpa In [3]: set_psf(mypsf)

sherpa In [4]: print(mypsf)
psfmodel.mypsf
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   mypsf.kernel frozen tmpjrv7xb58_simulate_p.psf
   mypsf.size   frozen   (256, 256)   (256, 256)   (256, 256)
   mypsf.center frozen   (128, 128)   (128, 128)   (128, 128)
   mypsf.radial frozen            0            0            1           
   mypsf.norm   frozen            1            0            1           

sherpa In [5]: mypsf.pars
Out[5]: ()
```

This is using the CIAO 4.13 version on Linux. I can provide files, but any PSF should do.

In this case I'd have expected `mypsf.pars` to return a tuple of `Parameter` objects (or similar) akin to other model components

```python
sherpa In [6]: gauss2d.g1()
Out[6]: <Gauss2D model instance 'gauss2d.g1'>

sherpa In [7]: g1.pars
Out[7]: 
(<Parameter 'fwhm' of model 'g1'>,
 <Parameter 'xpos' of model 'g1'>,
 <Parameter 'ypos' of model 'g1'>,
 <Parameter 'ellip' of model 'g1'>,
 <Parameter 'theta' of model 'g1'>,
 <Parameter 'ampl' of model 'g1'>)
```

**Comment by DougBurke** [comment]
This could be intentional or it's just an error in the convolution-style code. It's unclear, given the lack of documentation there, but my bet is the latter.

If you apply the psf model to a component - e.g.

```
m = mypsf(g1)
```

then I **believe** you can use `m.pars` (but I haven't tried, so confirmation from someone other than me would be nice).

There is the possibility that it only makes sense to have parameters on such a combined object, but then why does `print(mypsf)` talk about parameters...

**Comment by kglotfelty** [comment]
applying the psf just gets you the parameters of the model it's applied to

```python
sherpa In [7]: x = mypsf(g)

sherpa In [8]: x.pars
Out[8]: 
(<Parameter 'fwhm' of model 'g'>,
 <Parameter 'xpos' of model 'g'>,
 <Parameter 'ypos' of model 'g'>,
 <Parameter 'ellip' of model 'g'>,
 <Parameter 'theta' of model 'g'>,
 <Parameter 'ampl' of model 'g'>)
```

**Comment by DougBurke** [comment]
When I added the XSPEC convolution models I got the parameters to get "passed through" which I think makes more sense:

```
sherpa In [8]: mdl = xszashift.xmdl(xsapec.amdl)

sherpa In [9]: print(mdl)
xszashift.xmdl(xsapec.amdl)
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   xmdl.Redshift frozen            0       -0.999           10
   amdl.kT      thawed            1        0.008           64        keV
   amdl.Abundanc frozen            1            0            5
   amdl.redshift frozen            0       -0.999           10
   amdl.norm    thawed            1            0        1e+24

sherpa In [10]: mdl.pars
Out[10]:
(<Parameter 'Redshift' of model 'xmdl'>,
 <Parameter 'kT' of model 'amdl'>,
 <Parameter 'Abundanc' of model 'amdl'>,
 <Parameter 'redshift' of model 'amdl'>,
 <Parameter 'norm' of model 'amdl'>)

sherpa In [11]: xmdl.pars
Out[11]: (<Parameter 'Redshift' of model 'xmdl'>,)

sherpa In [12]: amdl.pars
Out[12]:
(<Parameter 'kT' of model 'amdl'>,
 <Parameter 'Abundanc' of model 'amdl'>,
 <Parameter 'redshift' of model 'amdl'>,
 <Parameter 'norm' of model 'amdl'>)

```

**Comment by DougBurke** [comment]
Notes to self:

```
In [1]: from sherpa.astro.ui import *
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: gauss1d.g1()
Out[2]: <Gauss1D model instance 'gauss1d.g1'>

In [3]: gauss1d.g2()
Out[3]: <Gauss1D model instance 'gauss1d.g2'>

In [4]: load_psf('bob', g1)

In [5]: conv = bob(g2)

In [6]: print(conv)
psfmodel.bob(gauss1d.g2)
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   g1.fwhm      frozen           10  1.17549e-38  3.40282e+38
   g1.pos       frozen            0 -3.40282e+38  3.40282e+38
   g1.ampl      frozen            1 -3.40282e+38  3.40282e+38
   g2.fwhm      thawed           10  1.17549e-38  3.40282e+38
   g2.pos       thawed            0 -3.40282e+38  3.40282e+38
   g2.ampl      thawed            1 -3.40282e+38  3.40282e+38

In [7]: conv.pars
Out[7]:
(<Parameter 'fwhm' of model 'g1'>,
 <Parameter 'pos' of model 'g1'>,
 <Parameter 'ampl' of model 'g1'>,
 <Parameter 'fwhm' of model 'g2'>,
 <Parameter 'pos' of model 'g2'>,
 <Parameter 'ampl' of model 'g2'>)

In [8]: print(bob)
psfmodel.bob
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   bob.kernel   frozen   gauss1d.g1
   bob.radial   frozen            0            0            1
   bob.norm     frozen            1            0            1

In [9]: bob.pars
Out[9]: ()
```

So, should

- `bob.pars` not be empty?
- should `conv` contain `bob.pars`?

I think so, but haven't dug through the code. I do note that the PSF model has different parameters when you have an array (where you get `size` and `center`) versus a model, and this could be "fun" - although I don't think we easily let you change the type of data stored in a PSF kernel so we can just require this constraint.

**Comment by kglotfelty** [comment]
Just a note that the `size` and `center` seem to come into existence when the PSF is `set` to a particular dataset

```python
In [1]: from sherpa.astro.ui import *                                                                                          

In [2]: gauss1d.g1()                                                                                                           
Out[2]: <Gauss1D model instance 'gauss1d.g1'>

In [3]: gauss1d.g2()                                                                                                           
Out[3]: <Gauss1D model instance 'gauss1d.g2'>

In [4]: load_psf('bob',g1)                                                                                                     

In [5]: print(bob)                                                                                                             
psfmodel.bob
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   bob.kernel   frozen   gauss1d.g1
   bob.radial   frozen            0            0            1           
   bob.norm     frozen            1            0            1           

In [6]: load_data("image.fits")                                                                   

In [7]: set_psf(bob)                                                                                                           

In [8]: print(bob)                                                                                                             
psfmodel.bob
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   bob.kernel   frozen   gauss1d.g1
   bob.size     frozen   (618, 619)   (618, 619)   (618, 619)
   bob.center   frozen   (309, 309)   (309, 309)   (309, 309)
   bob.radial   frozen            0            0            1           
   bob.norm     frozen            1            0            1           

In [9]: bob.pars                                                                                                               
Out[9]: ()
```

I guess it makes some sense since they values are derived from the dataset the PSF is applied to -- but still not included in the `.pars` .

**Comment by DougBurke** [comment]
Internally they're not treated like the other parameters, which both makes sense and is going to be "fun" to think about.

**Comment by DougBurke** [comment]
Harumph. This may well be trickier to try and fix than I have time for. Yegads!

**Comment by DougBurke** [comment]
So I don't forget: the following script - which may not make complete sense, I haven't looked too closely - creates the following with CIAO 4.13

```
# ignoring a data-conversion warnng message
[ 5.00000000e-01  1.00000000e+00  5.00000000e-01 -3.46944695e-17
  6.93889390e-17]
```

whereas in a version where I change `sherpa/instrument.py::PSFModel` with

```
-        Model.__init__(self, name)
+        Model.__init__(self, name, pars=(self.radial, self.norm))
```

then it errors out with

```
Traceback (most recent call last):
  File "../tst-pars.py", line 17, in <module>
    print(conv([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
  File "/home/dburke/sherpa/sherpa-work/sherpa/models/model.py", line 304, in __call__
    return self.calc([p.val for p in self.pars], *args, **kwargs)
  File "/home/dburke/sherpa/sherpa-work/sherpa/instrument.py", line 73, in calc
    return self.psf.calc(p[:nlhs], p[nlhs:],
  File "/home/dburke/sherpa/sherpa-work/sherpa/instrument.py", line 543, in calc
    psf_space_evaluation = self.model.calc(*args, **kwargs)
  File "/home/dburke/sherpa/sherpa-work/sherpa/instrument.py", line 179, in calc
    data = rhs(pr, *self.args, **self.kwargs)
  File "/home/dburke/sherpa/sherpa-work/sherpa/models/model.py", line 95, in cache_model
    vals = func(cls, pars, xlo, *args, **kwargs)
  File "/home/dburke/sherpa/sherpa-work/sherpa/models/basic.py", line 105, in calc
    return _modelfcts.box1d(*args, **kwargs)
TypeError: expected 3 parameters, got 5
```

which suggests that this is not going to be an easy change.

---

```
from sherpa.data import Data1D
from sherpa.models.basic import Box1D, Gauss1D
from sherpa.instrument import PSFModel

box = Box1D('box')
gauss = Gauss1D('gauss')

d = Data1D('data', [1, 2, 3, 4, 5], [1, 1, 1, 1, 1])

psf = PSFModel('psf', box)
box.xlow = 1.5
box.xhi = 3.5

conv = psf(box)
psf.fold(d)

print(conv([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
```

**Comment by DougBurke** [comment]
This could be related to 

- #296 

That is the psf model "parameters" should be labelled as something different to "a parameter which I can change during a fit", as these are more like "settings which I can adjust but not during a fit". I think.
