### ISSUE TITLE
what should we do when all data has been ignored?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1220]
This is a problem across our data objects (i.e. it's not just a DataPHA issue). I am using the main branch behavior but I don't think it significatly changes once we get #1219 (and its precursors) merged

When all the data has been masked out we can get a `DataErr` thrown, or `''` returned, or (for PHA) `"No noticed bins"`. This is not ideal.

Note that there's a `get_filter` issue and a more-general issue:

a) for `get_filter` we should have the same behavior however we've ignored the data
b) when we've filtered out all the data do we expect to always raise a `DataErr` when accessing the data, so `get_filter` but also data accessors either called directly like `get_x`, `get_xerr`, `get_indep`, `get_y`, `get_quality`, ..., or indirectly when plotting data, fitting, .... I think it's probably a per "approach" ca;; (ie for fitting throwing an error may make sense but for data accessors we might want to return an empty array)

# What is going on for `get_filter`

The `mask` attribute has three settings: `True` (created with `notice()`), `False` (created with `ignore()`), and an array of bools (created once you specify a limit with a `notice` or `ignore` call).  These three states can lead to different `get_filter` outputs **I think**, but there is also a DataErr that is being raised from some code paths and not others. For `mask` I understand the `True` and array of boleans, but I wonder if we need the `False` state.

# Examples

These examples shows`get_filter` for the moment- I'll add more later

## Data1D

```python
>>> from sherpa.data import Data1D
>>> d = Data1D('x', [1,2,3], [1,1,1])
/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/data.py:50: UserWarning: Converting array [1, 1, 1] to numpy array.
  warnings.warn("Converting array {} to numpy array.".format(array))
>>> d.get_filter(format='%.4f')
'1.0000:3.0000'
>>> d.ignore()
>>> d.get_filter(format='%.4f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/data.py", line 1084, in get_filter
    x = self.get_x(filter=True)
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/data.py", line 995, in get_x
    return self.get_evaluation_indep(filter, model, use_evaluation_space)[0]
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/data.py", line 1114, in get_evaluation_indep
    data_space = self._data_space.get(filter)
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/data.py", line 121, in get
    data = self.filter.apply(data)
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/data.py", line 441, in apply
    raise DataErr('notmask')
sherpa.utils.err.DataErr: mask excludes all data
>>> d.notice()
>>> d.get_filter(format='%.4f')
'1.0000:3.0000'
>>> d.ignore(1,2)
>>> d.get_filter(format='%.4f')
'3.0000'
>>> d.ignore(2,3)
>>> d.get_filter(format='%.4f')
''
```

## DataPHA (no quality)

```python
>>> import numpy as np
>>> from sherpa.astro.data import DataPHA
>>> pha = DataPHA('', np.array([1,2,3]), [1,1,1])
>>> pha.get_filter()
'1:3'
>>> pha.ignore()
>>> pha.get_filter()
'No noticed bins'
>>> pha.notice()
>>> pha.ignore(1,2)
>>> pha.get_filter()
'3'
>>> pha.ignore(2,3)
>>> pha.get_filter()
''
```

## DataPHA (with quality)

```python
>>> pha = DataPHA('', np.array([1,2,3]), [1,1,1], quality=[2,2,2], grouping=[1,1,1])
>>> pha.get_filter()
'1:3'
>>> pha.ignore_bad()
>>> pha.get_filter()
''
```

**Comment by DougBurke** [comment]
This also holds for `DataIMG` objects, which use a different path for the filter code, but there if you have no filter applied then `get_filter` returns `''` - perhaps it should return `'field()'`. It's not 100% obvious what a filter of `''` means in this case (things are improved by #1246 but it doesn't [yet] address that part).

See also #1247 for a brief discussion of `''` filters for images.

**Comment by DougBurke** [comment]
Here's an example from `plot_model` with PHA data (it's from the 4.14 beta 1 test so not quite main branch) - this is just to show we have things to work on here rather than picking on this one case:

```python
>>> from sherpa.astro.ui import *
>>> from sherpa.utils.logging import SherpaVerbosity
>>> with SherpaVerbosity('ERROR'):
...     load_pha('3c273.pi')
...
>>> d = get_data()
>>> d.mask
True
>>> set_source(powlaw1d.pl)
>>> plot_model()
>>> d.ignore()
>>> d.mask
False
```

So at this point I've removed all points. We get an error from `plot_model` but it is not ideal (i.e. it's not `DataErr("notmask")`).

```python
>>> plot_model()
Traceback (most recent call last):
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/utils/__init__.py", line 1547, in parse_expr
    lo = float(lo)
ValueError: could not convert string to float: 'No noticed bins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in plot_model
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/ui/utils.py", line 12552, in plot_model
    plotobj = self.get_model_plot(id, recalc=not replot)
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/astro/ui/utils.py", line 10291, in get_model_plot
    plotobj.prepare(d, self.get_model(id), self.get_stat())
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/astro/plot.py", line 191, in prepare
    old_filter = parse_expr(data.get_filter())
  File "/home/dburke/anaconda/envs/ciao414b1/lib/python3.8/site-packages/sherpa/utils/__init__.py", line 1549, in parse_expr
    raise TypeError("Invalid lower bound '%s'" % str(lo))
TypeError: Invalid lower bound 'No noticed bins'
```

If I instead remove all points by repeatedly ignoring data you would expect the same error, but this time `plot_model` returns with no error:

```python
>>> notice()
>>> d.mask
True
>>> d.ignore(0, 20)
>>> d.mask
array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])
>>> plot_model()
>>>
```

Argh - this last case is affected by #1024!

**Comment by DougBurke** [comment]
I had thought to special case the mask support so that if the mask is all `True` it gets converted to `mask=True` and if all `False` then `mask=False` but this breaks quite a lot of code which is expecting `mask` to be an array.

We could do the alternative - that is always convert `mask=True` to `[True] * n` and `mask=False` to `[False] * n` but that is also not possible since the `Filter` class does not know the size of the dataset it represents.

So either way requires a lot of internal code cleanup.
