### ISSUE TITLE
astropy 4.3 and it's FITS checks are causing us problems

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1226]
I have a test that manually creates a FITS file for a test. astopy-4.3 now notes that it's not a "correct" file and throws an error

```
E               OSError: No SIMPLE card found, this file does not appear to be a valid FITS file
```

Of course, we are now getting version 4.3 on the pip installs in our CI run.

This should be an easy change to the test.

**Comment by DougBurke** [comment]
Of course, the file does have a SIMPLE card so I don't understand...

**Comment by DougBurke** [comment]
For  [fake_rmf.fits.gz](https://github.com/sherpa/sherpa/files/6880792/fake_rmf.fits.gz) here's the header of the first block (after uncompressing)

```bash
% fold fake_rmf.fits | head
SIMPLE  = T
BITPIX  = 8
NAXIS   = 0
EXTEND  = T
END





```

and we get with astropy 4.3

```bash
% python -c 'from astropy.io import fits; fits.open("fake_rmf.fits")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dburke/anaconda/envs/sherpa-xspec/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 173, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/home/dburke/anaconda/envs/sherpa-xspec/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 408, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/home/dburke/anaconda/envs/sherpa-xspec/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 1090, in _readfrom
    raise OSError('No SIMPLE card found, this file does not '
OSError: No SIMPLE card found, this file does not appear to be a valid FITS file
```

**IF I COMPRESS THE FILE** I can load it in:

```
% gzip fake_rmf.fits
% python -c 'from astropy.io import fits; fits.open("fake_rmf.fits.gz")'
```

**Comment by DougBurke** [comment]
On AstroPys side would be `fverify`

```

                      FVERIFY V4.18 (CFITSIO V3.480)
                      ------------------------------

HEASARC conventions are being checked.

File: fake_rmf.fits

3 Header-Data Units in this file.

=================== HDU 1: Primary Array ===================

*** Error:   SIMPLE   mandatory keyword is not in logical fixed format:
SIMPLE  = T
          -------------------^
*** Error:   BITPIX   mandatory keyword is not in integer fixed format:
BITPIX  = 8
          -------------------^
*** Error:   NAXIS    mandatory keyword is not in integer fixed format:
NAXIS   = 0
          -------------------^

 5 header keywords

 Null data array; NAXIS = 0

=================== HDU 2: BINARY Table ====================

*** Error:   BITPIX   mandatory keyword is not in integer fixed format:
BITPIX  = 8
          -------------------^
*** Error:   NAXIS    mandatory keyword is not in integer fixed format:
NAXIS   = 2
          -------------------^
*** Error:   NAXIS1   mandatory keyword is not in integer fixed format:
NAXIS1  = 10
          -------------------^
*** Error:   NAXIS2   mandatory keyword is not in integer fixed format:
NAXIS2  = 5
          -------------------^
*** Error:   PCOUNT   mandatory keyword is not in integer fixed format:
PCOUNT  = 0
          -------------------^
*** Error:   GCOUNT   mandatory keyword is not in integer fixed format:
GCOUNT  = 1
          -------------------^
*** Error:   TFIELDS  mandatory keyword is not in integer fixed format:
TFIELDS = 3
          -------------------^
*** Error:   checking data fill: Data fill area invalid

 22 header keywords

 EBOUNDS  (3 columns x 5 rows)

 Col# Name (Units)       Format
   1 CHANNEL              I
   2 E_MIN                E
   3 E_MAX                E

=================== HDU 3: BINARY Table ====================

*** Error:   BITPIX   mandatory keyword is not in integer fixed format:
BITPIX  = 8
          -------------------^
*** Error:   NAXIS    mandatory keyword is not in integer fixed format:
NAXIS   = 2
          -------------------^
*** Error:   NAXIS1   mandatory keyword is not in integer fixed format:
NAXIS1  = 18
          -------------------^
*** Error:   NAXIS2   mandatory keyword is not in integer fixed format:
NAXIS2  = 5
          -------------------^
*** Error:   PCOUNT   mandatory keyword is not in integer fixed format:
PCOUNT  = 0
          -------------------^
*** Error:   GCOUNT   mandatory keyword is not in integer fixed format:
GCOUNT  = 1
          -------------------^
*** Error:   TFIELDS  mandatory keyword is not in integer fixed format:
TFIELDS = 6
          -------------------^
*** Error:   checking data fill: Data fill area invalid

 33 header keywords

 MATRIX  (6 columns x 5 rows)

 Col# Name (Units)       Format
   1 ENERG_LO             E
   2 ENERG_HI             E
   3 N_GRP                I
   4 F_CHAN               I
   5 N_CHAN               I
   6 MATRIX               E

++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++

 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         3
 2     EBOUNDS              Binary Table     0         8
 3     MATRIX               Binary Table     0         8

**** Verification found 0 warning(s) and 19 error(s). ****
```

**Comment by DougBurke** [comment]
It looks like what we needed was

```
SIMPLE  =                    T
BITPIX  =                    8
NAXIS   =                    0
EXTEND  =                    T
END
```

**Comment by DougBurke** [comment]
Let's see if https://github.com/sherpa/sherpa/pull/1223/commits/630574022f538c86265ba01c283b8ebc39ce41a0 works
