### ISSUE TITLE
Error when requiring colkeys when using get_ascii_data in crates.backend

### ISSUE THREAD

**Issue by dtnguyen2** [sherpa/sherpa#1262]
PR #1253 added the ```test_save_filter_data1``` in the file _sherpa/ui/tests/test_ui_unit.py_.  Unfortunately the said test fails when using ```crates```.

```
devel12-171: python fubar.py
Traceback (most recent call last):
  File "fubar.py", line 3, in <module>
    get_ascii_data('filter.dat', ncols=2, colkeys=['X', 'FILTER'])
  File "/proj/xena/ciaod/Linux/ciao_0824/ciao-4.14/lib/python3.8/site-packages/sherpa/astro/io/crates_backend.py", line 536, in get_ascii_data
    return get_table_data(filename, ncols, colkeys)[:3]
  File "/proj/xena/ciaod/Linux/ciao_0824/ciao-4.14/lib/python3.8/site-packages/sherpa/astro/io/crates_backend.py", line 602, in get_table_data
    for col in _require_tbl_col(tbl, name, cnames, make_copy, fix_type):
  File "/proj/xena/ciaod/Linux/ciao_0824/ciao-4.14/lib/python3.8/site-packages/sherpa/astro/io/crates_backend.py", line 276, in _require_tbl_col
    raise IOErr('reqcol', name, cnames)
sherpa.utils.err.IOErr: Required column 'X' not found in ['col1', 'col2']
```

```
devel12-169: cat filter.dat 
#TEXT/SIMPLE
# X FILTER
1 0
2 1
3 1
4 1
5 0
6 1
7 1
8 1
9 0
10 0
```
```
devel12-170: cat fubar.py
from sherpa.astro.io.crates_backend import get_ascii_data

get_ascii_data('filter.dat', ncols=2, colkeys=['X', 'FILTER'])
```

**Comment by DougBurke** [comment]
If we had something like #1069 we would see this sort of error on GH actions, but no one has time to look at it.

**Comment by dtnguyen2** [comment]
@DougBurke, so what is the final decision?  The CM group would like to have a fix in for this ASAP.  Thanks in advance

**Comment by DougBurke** [comment]
I was expecting someone to fix this. I provided information but I have a lot of other Sherpa issues I'm working on.
