### ISSUE TITLE
DataPHA objects without ARF/RMF only work for channel numbers starting with 1

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1305]
I create a `DataPHA` object from scratch because I'm fitting data that's not in an OGIP compliant format (it's been taken in a ground-based instrumentation lab for testing early development models of X-ray instrumentation). Because of it's origin, I don't have an ARF and RMF, so I'm just passing in `bin_lo` and `bin_hi`. When I start the channel numbering with 0 strange things happen. I saw this first in a plot, but traced it back to `DataPHA.get_x()`. Note the order order of the energies listed.
```
import numpy as np
from sherpa.astro.data import DataPHA
bins = np.array([.2, .4, .6, .8, 1.])
testpha = DataPHA(name='testdata', channel=np.arange(4), counts=[5, 6, 7, 8],
              bin_lo=bins[:-1], bin_hi=bins[1:])
testpha.set_analysis('energy')
testpha.get_x()

>>> array([0.9, 0.3, 0.5, 0.7])
```

It also fails for channel numbers starting > 1, but with a different error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in _channel_to_energy(self, val, group, response_id)
   1910         try:
-> 1911             return (elo[val] + ehi[val]) / 2.0
   1912         except IndexError:

IndexError: index 4 is out of bounds for axis 0 with size 4

During handling of the above exception, another exception occurred:

DataErr                                   Traceback (most recent call last)
<ipython-input-63-29682d4539c6> in <module>
      5               bin_lo=bins[:-1], bin_hi=bins[1:])
      6 testpha.set_analysis('energy')
----> 7 testpha.get_x()

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in get_x(self, filter, response_id)
   3092         # We want the full channel grid with no grouping.
   3093         #
-> 3094         return self._from_channel(self.channel, group=False, response_id=response_id)
   3095 
   3096     def get_xlabel(self):

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in _channel_to_energy(self, val, group, response_id)
   1911             return (elo[val] + ehi[val]) / 2.0
   1912         except IndexError:
-> 1913             raise DataErr('invalidchannel', val)
   1914 
   1915     def _energy_to_channel(self, val):

DataErr: invalid channel number: [4 5 6 7]
```

I have a fix that I will put into a PR shortly.

Two notes:
- This is relatively easy to work around. Simply start counting channels at 1. Alternatively, I can make up an ARF and RMF (using make_diogonal_response and friends) and this code path won't be executed. I still think it's worth a fix in general.
- This code area might profit from #1174. Instead of having multiple, similar code path #1174 would unify that to just one, hopefully simplifying the implementation and testing.

This is not urgent can can be dealt with after 4.14 is out.

**Comment by DougBurke** [comment]
So, the issue here I claim is that

- `bin_lo`/`bin_hi` are a "post OGIP" addition, and so come with no documentation
- they are used to allow Chandra grating data avoid a RMF (at least as far as I can tell)
- the Chandra grating data has the  `bin_lo`,`bin_ho` values in descending value (since energy goes up with channel wavelength has to go down)

For example

```
% dmlist 3c120_heg_1.pha.gz"[cols channel,bin_lo,bin_hi][#row=:3]" data,clean
#  CHANNEL    BIN_LO               BIN_HI
          1             21.47750               21.480
          2              21.4750             21.47750
          3             21.47250              21.4750
% dmlist 3c120_heg_1.pha.gz"[cols channel,bin_lo,bin_hi][#row=8190:]" data,clean
#  CHANNEL    BIN_LO               BIN_HI
       8190               1.0050              1.00750
       8191              1.00250               1.0050
       8192                  1.0              1.00250
```

So, if you reverse your `bins` array I claim it  is likely to work better - although you still get the strange behaviour when channels start at non-1:

```
>>> import numpy as np
>>> from sherpa.astro.data import DataPHA
>>> bins = np.array([.2, .4, .6, .8, 1.])
>>> rbins = bins[::-1]
>>> bin_lo = rbins[1:]  # note the swap in ordering
>>> bin_hi = rbins[:-1]
>>> test1 = DataPHA("x1", np.arange(4) + 1, [4, 5, 6, 7], bin_lo=bin_lo, bin_hi=bin_hi)
>>> test0 = DataPHA("x1", np.arange(4) + 0, [4, 5, 6, 7], bin_lo=bin_lo, bin_hi=bin_hi)
>>> test5 = DataPHA("x1", np.arange(4) + 5, [4, 5, 6, 7], bin_lo=bin_lo, bin_hi=bin_hi)
>>> for d in [test0, test1, test5]:
...     d.set_analysis("energy")
... 
>>> test1.get_x()
array([13.94822108, 18.08102733, 25.83003904, 46.49407027])
>>> test0.get_x()
array([46.49407027, 13.94822108, 18.08102733, 25.83003904])
>>> test5.get_x()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-2/sherpa/astro/data.py", line 4204, in get_x
    return self._from_channel(self.channel, group=False, response_id=response_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-2/sherpa/astro/data.py", line 2669, in _channel_to_energy
    raise DataErr('invalidchannel', val) from None
sherpa.utils.err.DataErr: invalid channel number: [4 5 6 7]
```

Unfortunately this is not fixed by #2118, but again this is, I believe, problems with the bin_lo/hi code which we just do not have good tests/documentation.

**Comment by hamogu** [comment]
So, let me put my HETG hat on with some knowledge that I have now and I may have had (but didn't think about in 2021) or that I only learned after.

OGIP specifies the minimum set of columns. I don't think it says that there can't be any additional columns that might be useful. And that's what the bin_hi/bin_lo does. It's been added as a convenience for the user to the files that CIAO produces for the Chandra gratings. It's meant (based on what people who where already working for the CXC back then tell me, I think we have written docs but it's not very relevant as we will see) just as a convenience for plotting. Back in the day, we didn't have Sherpa, we didn't have ISIS, and XSPEC just didn't look a good as it does today. Grating spectra are pretty peaked, so the goal here is simply to allow a quick plot of wavelength vs. count number. For that, having bin_lo/bin_hi in the PHA file means that you just have to load a single file into IDL or Perl or your language of choice to make that plot. 

That said, I think the best approach for Sherpa would be to not surface those columns at all. Options include ignoring them when loading PHA files, deleting them, hiding them, or at the very least not offer them in the `DataPHA` constructor. Having them as parameters in the constructor obviously confuses users like me - it would be better not to allow setting them. We could load them if present in an input file for backwards compatibility, but never set them manually.

Since XMM/RGS does not have those columns, I'm pretty sure that Sherpa can handle data without them just fine.
