### ISSUE TITLE
python 3.10: python setup.py install fails in grplib-4.9 / stklib-4.11

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1316]
```
% pythons setup.py install
...
... looks good
...
... but then
...
checking for python3.1... /home/dburke/anaconda/envs/py310/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >='2.7'... yes
checking for the distutils Python package... no
configure: error: cannot import Python module "distutils".
Please check your Python installation. The error was:
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
configure: error: ./configure failed for grplib-4.9
```

Unsurprisingly you get the same problem with `pip install .` but it's easier to see the errors with the above.

**Comment by DougBurke** [comment]
You can turn off the problem components in the `setup.cfg` file (I'm surprised that `region-4.14` doesn't fail, but maybe that's because we don't actually build a python interface in `extern/` like we do the other two):

```
%  git diff
diff --git a/setup.cfg b/setup.cfg
index 8cacc6fd..b845937d 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -16,14 +16,14 @@ bdist_wheel = sherpa_config bdist_wheel
 #configure=None

 # GROUP Python module
-#disable-group=True
+disable-group=True
 #group-location=build/lib/python2.7/site-packages/group.so

 # Additional flags to be passed to libgrp build
 #group-cflags=

 # File Stack Python module
-#disable-stk=True
+disable-stk=True
 #stk-location=build/lib/python2.7/site-packages/stk.so

 # FFTW Library
```

**Comment by DougBurke** [comment]
With

- `disable-group` and `disable-stack`
- PR #1317 
- PR #1318 

I was able to get a build with Python 3.10 + astropy + matplotlib passing the tests (including the data tests). So that's good.

**Comment by DougBurke** [comment]
Hmmm. It looks like I now can build with python 3.10. I know there have been a large number of updates to setuptools recently, and maybe there's also been a change to python 3.10/distutils.

**Comment by DougBurke** [comment]
However, trying to build XSPEC support throws up the following - it may be related to #1328 which recently got merged

```
pip install -e .
Obtaining file:///home/dburke/sherpa/sherpa-master
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dburke/miniconda3/envs/sherpa310/bin/python /home/dburke/miniconda3/envs/sherpa310/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpgvdnyjp8
       cwd: /home/dburke/sherpa/sherpa-master
  Complete output (28 lines):
  Traceback (most recent call last):
    File "/home/dburke/miniconda3/envs/sherpa310/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/dburke/miniconda3/envs/sherpa310/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/dburke/miniconda3/envs/sherpa310/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5h6dbpz3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-5h6dbpz3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5h6dbpz3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-5h6dbpz3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 65, in <module>
      version=versioneer.get_version(),
    File "/home/dburke/sherpa/sherpa-master/versioneer.py", line 1724, in get_version
      return get_versions()["version"]
    File "/home/dburke/sherpa/sherpa-master/versioneer.py", line 1656, in get_versions
      cfg = get_config_from_root(root)
    File "/home/dburke/sherpa/sherpa-master/versioneer.py", line 346, in get_config_from_root
      VCS = parser.get("versioneer", "VCS")  # mandatory
    File "/home/dburke/miniconda3/envs/sherpa310/lib/python3.10/configparser.py", line 782, in get
      d = self._unify_values(section, vars)
    File "/home/dburke/miniconda3/envs/sherpa310/lib/python3.10/configparser.py", line 1153, in _unify_values
      raise NoSectionError(section) from None
  configparser.NoSectionError: No section: 'versioneer'
  ----------------------------------------
WARNING: Discarding file:///home/dburke/sherpa/sherpa-master. Command errored out with exit status 1: /home/dburke/miniconda3/envs/sherpa310/bin/python /home/dburke/miniconda3/envs/sherpa310/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpgvdnyjp8 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/dburke/miniconda3/envs/sherpa310/bin/python /home/dburke/miniconda3/envs/sherpa310/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpgvdnyjp8 Check the logs for full command output.
```
