### ISSUE TITLE
Problem with xspec-modelsonly=12.11.1 conda build

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1395]
I have the following error when I build a conda install against our xspec-modelsonly=12.11.1 build (which I have now also re-created by running a GH action that ran successfully last Friday but now fails today with the same error, so something has changed in conda-land over the week-end - see https://github.com/sherpa/sherpa/actions/runs/1669242264):

```
% python -c 'from sherpa.astro import xspec;print(xspec.get_xsversion())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-main/sherpa/astro/xspec/__init__.py", line 110, in <module>
    from .utils import ModelMeta, version_at_least, equal_or_greater_than
  File "/home/dburke/sherpa/sherpa-main/sherpa/astro/xspec/utils.py", line 21, in <module>
    from . import _xspec
ImportError: /home/dburke/anaconda/envs/sherpa-main-temp/lib/././libreadline.so.8: undefined symbol: tputs
```

I believe I have "followed the correct steps", which are based on `.github/scripts/setup_xspec_ds9.sh` and I followed successfully with xspec-modelsonly=12.10.1. I have a single "conda create" line because things can get a little funky trying to get a consistent environment with something built so-long-ago (in this case the xspec-modelsonly package). 

```
% conda create -n=sherpa-main-temp -c xspec/label/test python=3.7 xspec-modelsonly=12.11.1 gcc_linux-64 gxx_linux-64 gfortran_linux-64
...
% conda activate sherpa-main-temp

% git diff setup.cfg
diff --git a/setup.cfg b/setup.cfg
index 8cacc6fd..70c7db52 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -59,6 +59,11 @@ bdist_wheel = sherpa_config bdist_wheel
 #wcs-lib-dirs=build/lib
 #wcs-libraries=wcs

+fftw=local
+fftw-include_dirs=/home/dburke/anaconda/envs/sherpa-main-temp/include
+fftw-lib-dirs=/home/dburke/anaconda/envs/sherpa-main-temp/lib
+fftw-libraries=fftw3
+

 [build_sphinx]
 source-dir = docs
@@ -108,3 +113,31 @@ source-dir = docs
 #wcslib_libraries = wcs
 #gfortran_lib_dirs = None
 #gfortran_libraries = gfortran
+
+with-xspec = True
+xspec_version = 12.11.1
+xspec_lib_dirs = /home/dburke/anaconda/envs/sherpa-main-temp/lib
+xspec_include_dirs = /home/dburke/anaconda/envs/sherpa-main-temp/include

% pip install -e . --verbose
...
```

For reference the conda environment is:

```
% conda list
# packages in environment at /home/dburke/anaconda/envs/sherpa-main-temp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
_sysroot_linux-64_curr_repodata_hack 3                   haa98f57_10
binutils_impl_linux-64    2.35.1               h27ae35d_9
binutils_linux-64         2.35.1              h454624a_30
ca-certificates           2021.10.26           h06a4308_2
certifi                   2021.10.8        py37h06a4308_0
cfitsio                   3.490                h14c3975_2    xspec/label/test
fftw                      3.3.9                h27cfd23_1
gcc_impl_linux-64         9.3.0               h6df7d76_17
gcc_linux-64              9.3.0               h1ee779e_30
gfortran_impl_linux-64    9.3.0               h5abd6ed_17
gfortran_linux-64         9.3.0               hf47db2c_30
gsl                       2.4                  h14c3975_4
gxx_impl_linux-64         9.3.0               hbdd7822_17
gxx_linux-64              9.3.0               h7e70986_30
kernel-headers_linux-64   3.10.0              h57e8cba_10
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-devel_linux-64     9.3.0               hb95220a_17
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran-ng            9.3.0               ha5ec8a7_17
libgfortran5              9.3.0               ha5ec8a7_17
libgomp                   9.3.0               h5101ec6_17
libstdcxx-devel_linux-64  9.3.0               hf0c5c8d_17
libstdcxx-ng              9.3.0               hd4cf53a_17
ncurses                   6.3                  h7f8727e_2
numpy                     1.21.5                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0
pip                       21.2.2           py37h06a4308_0
python                    3.7.11               h12debd9_0
readline                  8.1.2                h7f8727e_0
setuptools                58.0.4           py37h06a4308_0
sherpa                    4.14.0+111.g1a6da055.dirty           dev_0    <develop>
sqlite                    3.37.0               hc218d9a_0
sysroot_linux-64          2.17                h57e8cba_10
tk                        8.6.11               h1ccaba5_0
wheel                     0.37.1             pyhd3eb1b0_0
xspec-modelsonly          12.11.1              h6578b86_2    xspec/label/test
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7f8727e_4
```

The XSPEC libs reference `readline`:

```
% ldd /home/dburke/anaconda/envs/sherpa-main-temp/lib/libXS.so  | grep readline
        libreadline.so.8 => /home/dburke/anaconda/envs/sherpa-main-temp/lib/./libreadline.so.8 (0x00007f9bc6f05000)
% ldd /home/dburke/anaconda/envs/sherpa-main-temp/lib/libXSFunctions.so  | grep readline
        libreadline.so.8 => /home/dburke/anaconda/envs/sherpa-main-temp/lib/././libreadline.so.8 (0x00007f6eaf6f7000)
% ldd /home/dburke/anaconda/envs/sherpa-main-temp/lib/libXSModel.so  | grep readline
        libreadline.so.8 => /home/dburke/anaconda/envs/sherpa-main-temp/lib/./././libreadline.so.8 (0x00007f45682e8000)
% ldd /home/dburke/anaconda/envs/sherpa-main-temp/lib/libXS.so  | grep readline
        libreadline.so.8 => /home/dburke/anaconda/envs/sherpa-main-temp/lib/./libreadline.so.8 (0x00007fa7fe269000)
% ldd /home/dburke/anaconda/envs/sherpa-main-temp/lib/libXSUtil.so  | grep readline
%
```

If I check `libreadline` it is indeed missing `tputs`:

```
% nm /home/dburke/anaconda/envs/sherpa-main-temp/lib/libreadline.so.8 | grep tputs
                 U tputs
```

There is `libtinfo` in this directory with this symbol - are we just not setting up the necessary linkline?

```
% nm -p /home/dburke/anaconda/envs/sherpa-main-temp/lib/libtinfo.so.6.3 | grep tputs
000000000001ccd0 T tputs
000000000001c8f0 T tputs_sp
```

**Comment by DougBurke** [comment]
From an investigation by @Marie-Terrell it looks like this can be work-around with 

```
% conda install 'readline<8.1.2'
```

**Comment by harlantc** [comment]
opened an issue with the conda people at https://github.com/ContinuumIO/anaconda-issues/issues/12794
