### ISSUE TITLE
ignore_bad and clearing out the quality array

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1427]
Once you've set the quality array of a DataPHA dataset and called `ignore_bad`, what should happen when you remove the quality array:

This is with CIAO 4.14 but it's the same in the current main branch:

```
sherpa-4.14.0> load_arrays(1, [1, 2, 3, 4], [1, 0, 2, 7], DataPHA)

sherpa-4.14.0> get_dep(filter=False)
array([1., 0., 2., 7.])

sherpa-4.14.0> get_dep(filter=True)
array([1., 0., 2., 7.])

sherpa-4.14.0> set_quality([0, 0, 2, 0])

sherpa-4.14.0> get_dep(filter=False)
array([1., 0., 2., 7.])

sherpa-4.14.0> get_dep(filter=True)
array([1., 0., 2., 7.])
```

So far so good: the dependent axis hasn't changed (as we've not applied a filter). Let's change that and ignore the "bad quality" points:

```
sherpa-4.14.0> ignore_bad()

sherpa-4.14.0> get_dep(filter=False)
array([1., 0., 2., 7.])

sherpa-4.14.0> get_dep(filter=True)
array([1., 0., 7.])
```

So, with `filter=True` we can see that we have ignored the channel=3 bin (as the third element of the quality array is  not 0). Again, so far so good.

Now what happens if we clear the quality array?

```
sherpa-4.14.0> set_quality(None)

sherpa-4.14.0> get_data().quality is None
True

sherpa-4.14.0> get_dep(filter=False)
array([1., 0., 2., 7.])

sherpa-4.14.0> get_dep(filter=True)
array([1., 0., 7.])
```

Hmmm. We are still filtering by the bad data element.

Ideally  the last call would return `[1, 0, 2, 7]` here, as the "bad" filter has now gone.

Operationally this may be harder to do whilst still keeping other filters. I need to investigate. 

This came out of looking at #1160 (again).

**Comment by hamogu** [comment]
One might say that changing the quality automatically removes the filter. In practice, one either uses the quality (and calls "ignore_bad" right after loading the data) or not, it's not something to repeatedly change and switch on or off.

**Comment by DougBurke** [comment]
If you change the grouping then the quality will likely change (e.g. those channels where the group didn't match the grouping criterion; normally the last group). 

There is the choice of "we just error out" if things change, but even if we do this we need to identify what those conditions are. And I'm not yet convinced that this is the right approach, but I haven't thought about it enough. There is existing support for "hey, calling ignore_bad means that you clear out the existing filter", but it is implemented "strangely".

**Comment by DougBurke** [comment]
On a related issue: at the moment once you call `ignore_bad` you can't "remove" this. Well, there are things you can do but it relies on understanding what the system is doing and depending on what you have done it is not obvious it is always possible.

This may be okay, but I just wanted to mention it. I believe @hamogu has secret desires to allow you to select subsets of the quality array; that is to treat it more like a set of flags we can turn on/off individually rather than an all-or-nothing approach, where making the setting more dynamic would be needed.

**Comment by anetasie** [comment]
It might be useful to have this OGIP page for the reference:
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node7.html

This page contains a note:

> Within XSPEC, Qual=1 and Qual=5 rows will never be accessible and Qual=2 may be ignored using the “ignore bad" command.

**Comment by DougBurke** [comment]
I am very aware of that page and I believe the documentation already links to it but please add an issue if you find out somewhere explicit where it should be mentioned.

The way we handle things is different to XSPEC - since I believe they actually just drop the 1/5 channels when the file is read in so it's never seen - whereas we'd want to keep them but presumably always remove them from the user (this then would allow you to write out the "same" PHA file as you read in if needed, for some definition of "same"). 

Of course, we also allow a user to change the quality array - e.g. when regrouping the data- so for this case do we always want the "bad" channels marked as bad - which is different to XSPEC (the application; not checked pyxspec). This would mean once a channel was marked as a 1 or 5 (to use the XSPEC values) then it  is always going to be bad, no matter what the user does. I think this is okay (and it would be hard I think to work around), but I can imagine cases where you might want to reset those quality values (but only rarely which might well support the view of "well, you need to edit the file outside of sherpa and read it back in"). This is one of those "edge cases" we need to explote.

**Comment by anetasie** [comment]
I would say that Sherpa should not allow user to update the channels with quality 1 and 5, and go with this solution:
> "well, you need to edit the file outside of sherpa and read it back in"

**Comment by DougBurke** [comment]
For my reference, this behaviour still holds in not-quite-finalized 4.17.0

```
>>> from sherpa.astro.ui import *
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> load_arrays(1, [1,2, 3,4], [1,0, 2, 7], DataPHA)
>>> get_dep(filter=True)
array([1., 0., 2., 7.])
>>> get_dep(filter=False)
array([1., 0., 2., 7.])
>>> set_quality([0, 0, 2, 0])
>>> get_dep(filter=False)
array([1., 0., 2., 7.])
>>> get_dep(filter=True)
array([1., 0., 2., 7.])
>>> ignore_bad()
dataset 1: 1:4 -> 1:2,4 Channel
>>> get_dep(filter=False)
array([1., 0., 2., 7.])
>>> get_dep(filter=True)
array([1., 0., 7.])
>>> set_quality(None)
>>> get_data().quality is None
True
>>> get_dep(filter=False)
array([1., 0., 2., 7.])
>>> get_dep(filter=True)
array([1., 0., 7.])
>>> ignore_bad()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in ignore_bad
  File "/lagado.real/sherpa/sherpa-1/sherpa/astro/ui/utils.py", line 7523, in ignore_bad
    data.ignore_bad()
  File "/lagado.real/sherpa/sherpa-1/sherpa/astro/data.py", line 3489, in ignore_bad
    raise DataErr("noquality", self.name)
sherpa.utils.err.DataErr: data set '' does not specify quality flags
>>> 
```
