### ISSUE TITLE
Do we want to add validation to Data classes?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1436]
We've worked through most of the existing issues already, but we can still end up in a situation where a user can do something that causes downstream problems. My assumption is that we can mitigate the vast-majority of them by adding some form of validation to the `Data` hierarchy, but that is yet to be proven by design or code (they're being worked on). I wanted to have an issue to point to for that work.

# Example

Here's an example of the problem, with CIAO 4.14 but any version would do. The problem here is that the independent and dependent axes do not match, so a down-stream consumer of the data - in this case the `get_dep` call - ends up having to catch this case and report an error (or maybe you get a NumPy or Python error raised). Ideally the data could never be created in the first place (aka "Make Invalid States Unrepresentable").

## using the UI interface

```
sherpa-4.14.0> load_arrays(1, [1, 2, 3], [1, 2])

sherpa-4.14.0> ignore(3, None)

sherpa-4.14.0> get_dep()
array([1, 2])

sherpa-4.14.0> get_dep(filter=True)
DataErr: size mismatch between mask and data array
```

## directly using the `Data` interface

```
sherpa-4.14.0> d = Data1D('x', [1, 2, 3], [1, 2])
/home/dburke/anaconda/envs/ciao414/lib/python3.8/site-packages/sherpa/data.py:88: UserWarning: Converting array [1, 2] to numpy array.
  warnings.warn("Converting array {} to numpy array.".format(array))

sherpa-4.14.0> d.get_dep(filter=True)
array([1, 2])

sherpa-4.14.0> d.ignore(3, None)

sherpa-4.14.0> d.mask
array([ True,  True, False])

sherpa-4.14.0> d.get_dep(filter=True)
DataErr: size mismatch between mask and data array
```

# What validations could be done

- convert values to numpy arrays (we do this for the independent and dependent axes but not for other fields, such as `staterror`
- is everything a 1D array
- do we have the correct number of independent axes
- do the various fields (e.g. independent, dependent, errors, ...) have the same size
- do we want to convert data types - normally to float but the PHA case has a number of integer cases

# What would it mean

If we only ever created a data object and then treated those fields in the object as immutable this would be a lot easier. However, we have never enforced this so there may well be use cases that rely on the existing approach, and even if not we already have places where we want to allow fields to be changed (e.g. grouping of PHA data). We could make it that the independent and dependent axes are immutable, which would make some cases easier to reason about, but I wonder whether this would stop legitimate use cases (and our existing "fake data" for the PHA case would have to be changed if we did this).

So, if we do allow fields to be changed, what to do with a data object like

```
d = Data1D('x', [1, 2, 3], [2, 4, 3], [0.2, 0.2, 0.4])
```

and then you want to change the independent axis to a different size. Should such a call

1. error out and make the user explicitly clear out the existing fields - in this case setting both `y` and `staterror`  to `None` - first 
2. automatically clear out the other fields, setting them to `None`
3. or change the fields (i.e. clip the arrays or fill them with 0's) to match the new size

My current thinking is that option 2 is preferable but 1 is a lot easier to code.

Note that in this case trying to set the `staterror` field to a different size would be an error. You need to change the independent axis to change the "number of elements".

# Problem areas

In general we do seem to have a system where the independent and dependent axes being forced to be the same size works (i.e. we can think of it as an invariant). There are a number of test cases that need to be re-worked, but they are - in general - not fundamental problems but just require changes to how the test data is created.

However, the handling of PHA data explicitly breaks the relation between the independent and dependent axes thanks to 

- grouping, which means that there is a mapping from the actual data to the data used in analysis (the "effective" independent and dependent axes have the same size, but it complicates things)
- the RMF data class is "interesting" since it is represented as a `Data` object but it explicitly doesn't have a one-to-one match of the independent and dependent axes

It's fun trying to find out what this means and whether it means it's just not worth the effort.

**Comment by DougBurke** [comment]
Here's a fun one: say we have checks for length/size - e.g.

```
>>> import numpy as np
>>> from sherpa.data import Data1D
>>> d = Data1D("x", np.arange(12), np.ones(12))
>>> print(d)
name      = x
x         = Int64[12]
y         = Float64[12]
staterror = None
syserror  = None
```

so that

```
>>> d.y = [2, 3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-main/sherpa/utils/__init__.py", line 171, in __setattr__
    object.__setattr__(self, name, val)
  File "/home/dburke/sherpa/sherpa-main/sherpa/data.py", line 742, in y
    self._set_related("y", val)
  File "/home/dburke/sherpa/sherpa-main/sherpa/data.py", line 723, in _set_related
    raise DataErr("mismatch",
sherpa.utils.err.DataErr: size mismatch between indep (12) and y (2)
>>> d.y = np.arange(12).reshape(4, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-main/sherpa/utils/__init__.py", line 171, in __setattr__
    object.__setattr__(self, name, val)
  File "/home/dburke/sherpa/sherpa-main/sherpa/data.py", line 742, in y
    self._set_related("y", val)
  File "/home/dburke/sherpa/sherpa-main/sherpa/data.py", line 723, in _set_related
    raise DataErr("mismatch",
sherpa.utils.err.DataErr: size mismatch between indep (12) and y (4)
>>> d.indep = ([2], [3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-main/sherpa/utils/__init__.py", line 171, in __setattr__
    object.__setattr__(self, name, val)
  File "/home/dburke/sherpa/sherpa-main/sherpa/data.py", line 806, in indep
    self._data_space = self._init_data_space(self._data_space.filter, *val)
  File "/home/dburke/sherpa/sherpa-main/sherpa/data.py", line 1275, in _init_data_space
    raise DataErr("mismatch", "independent axis", "data")
sherpa.utils.err.DataErr: size mismatch between independent axis and data
```

Seems good. However, we can reshape the `y` attribute so it's 2D:

```
>>> d.y.resize(4, 3)
>>> print(d)
name      = x
x         = Int64[12]
y         = Float64[12]
staterror = None
syserror  = None
>>> d.y
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
>>> d.y.shape
(4, 3)
```

This may well be something we just live with (it's something a user can do now anyway, whereas the checks above need a PR or two to implement).

**Comment by hamogu** [comment]
related: #895 

I think there is a line between reasonable validation and stopping the user from intentionally breaking things. We should to the former (e.g., see #895) it is very easy to accidentally pass in x, y, staterr, etc. fields that don't match; we should not waste our effort on the latter. Python being Python, it will eventually throw an error and allow users to interactively debug things so I don't think we have to guard against highly unlikely errors like actively reshaping the y array of a 1D dataset into multiple dimensions.
