### ISSUE TITLE
histogram1d/2d issue

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1601]
With #1477 now landed, the following code - which is based on the `sherpa.utils.histogram1d` examples - now fails:

```
>>> from sherpa.ui import dataspace1d, get_indep
>>> dataspace1d(1, 10, 1)
>>> lo, hi = get_indep()
>>> print(lo)
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
>>> print(hi)
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
>>> from sherpa.utils import histogram1d
>>> n = histogram1d([2, 1, 0, 3, 2, 7, 5, 4, 9, 12], lo, hi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/miniconda3/envs/CIAOX/lib/python3.8/site-packages/sherpa/utils/__init__.py", line 2105, in histogram1d
    x_lo.sort()
ValueError: sort array is read-only
```

The problem is that the independent axis (which is internally stored away within `DataSpace1D`/`EvaluationSpace1D` as ` `PointAxis` or `InegratedAxis`) is now marked as "read only", and - **for some reason** - the `histogram1d` routine calls `sort` on the input `lo` and `hi` arrays.

There's several possible fixes

1. the user can just copy the arrays - e.g. `histogram1d(vals, lo.copy(), hi.copy())`
2. the `histogram1d` routine can internally call `copy`
3. we do away with sorting the input arguments in `histogram1d` and just make it a pre-condition on calling the routine (e.g. that the data is sorted)
4. we remove the read-only change added in #1477

Option 1 is short-term.
Option 2 is easy.
Option 3 is what I think I'd prefer.
Option 4 is, to me, a non-starter (as it was added to ensure things like this don't happen!).

**Comment by DougBurke** [comment]
I note that the same issue holds for the `histogram2d` routine in `sherpa.utils`. There's also `get_error_estimates` that **may** call `sort` on the input argument, but there's a case - not a really strong one, but not something that can just be ignored - to say that in this case the user knows this happens and so it's okay/expected.
