### ISSUE TITLE
Should the sherpa.astro.ui class wrap these models?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1647]
From https://github.com/sherpa/sherpa/issues/215#issuecomment-1342770339 I've realised we wrap a few models that probably aren't that usefuil (but I can't guarantee it)

These are models where `create_model_component(name, "mdl")` fail:

```
*FAILED* absorptionvoigt
*FAILED* arfmodelnopha
*FAILED* arfmodelpha
*FAILED* emissionvoigt
*FAILED* knninterpolator
*FAILED* rmfmodelnopha
*FAILED* rmfmodelpha
*FAILED* rspmodel
*FAILED* rspmodelnopha
*FAILED* rspmodelpha
*FAILED* template
*FAILED* templatemodel
```

the `*voigt* ones can be skipped as they are meant to fail. An example of an "actual problem":

```
>>> from sherpa.astro.ui import *
>>> rspmodel.foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-pr/sherpa/ui/utils.py", line 644, in __getattr__
    return self(name)
  File "/home/dburke/sherpa/sherpa-pr/sherpa/ui/utils.py", line 637, in __call__
    m = self.modeltype(name, *self.args, **self.kwargs)
TypeError: RSPModel.__init__() missing 2 required positional arguments: 'rmf' and 'model'
```

**Comment by hamogu** [comment]
It's amazing where you can end up following just some train of thought from just "some minor code clean-up" (https://github.com/sherpa/sherpa/pull/1638)!
