### ISSUE TITLE
DataPHA notice bkg_id oddity

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1709]
Noticed during code review of #1708 

```
>>> from sherpa.astro.data import DataPHA
>>> pha = DataPHA("src", [1, 2], [2, 3])
>>> bkg = DataPHA("bkg", [1, 2], [0, 1])
>>> pha.set_background(bkg, id="up")
>>> pha.notice(lo=2, bkg_id="up")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/data.py", line 4673, in notice
    old_bkg_units = bkg.units
AttributeError: 'NoneType' object has no attribute 'units'
```

If we use an integer then it's okay:

```
>>> pha.set_background(bkg, id=1)
>>> pha.notice(lo=2, bkg_id=1)
```

It's an easy bug to fix (the bkg_id parameter can take a sequence of objects, and the way that the code tried to identify this case used np.iterable, but unfortunately a string is iterable and it didn't check for that case).

**Comment by DougBurke** [comment]
This doesn't appear to be a problem for the UI case, but that appears to be because we don't let `bkg_id` be a sequence of ids there. Which we probably want to - but then we should look at other background commands to see what makes sense...

**Comment by DougBurke** [comment]
Just to note that this is *technically* the sort of bug that adding typing information would catch. I say technically since python's "type system" is not really expressive enough to guarantee that it can be done in a readable/useful manner.
