### ISSUE TITLE
doctestplus wibbles

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1719]
With the doctestlpus change I now see this behavior when pytest-doctestplus is installed

- pytest works
-  pytest --doctest-plus works
- running the tests for just a single file (e.g. test_astro_data.py) can fail

So, with docterstplusnot installed the following works (you get warnings about the unrecognised doctest settings but that's expected):

```
% pytest sherpa/astro/tests/test_astro_data.py
...
============================================================================ 485 passed, 7 xfailed, 5 warnings in 15.85s ============================================================================
```

If I then do

```
% pip install pytest-doctestplus
...
% pytest sherpa/astro/tests/test_astro_data.py 
...
============================================================================================= FAILURES ==============================================================================================
________________________________________________________________ [doctest] test_astro_data.test_notice_channel_grouping_outofbounds _________________________________________________________________
1352     Note that filters outside the range end up including the first or
1353     last bin (because it gets reset to the limit), which we
1354     probably do not want (for the low edge, for the upper
1355     edge we are probably lucky due to < rather than >=).
1356 
1357     The groups are such that the first group has channels
1358     1-17 and the last group 677-1024, which have mid-points
1359     9 and 850.5, hence the 9:850 as the default filter.
1360 
1361     >>> pha.apply_grouping(pha.channel, pha._min)
UNEXPECTED EXCEPTION: NameError("name 'pha' is not defined")
Traceback (most recent call last):
  File "/lagado2.real/local/anaconda/envs/sherpa-xspec/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest test_astro_data.test_notice_channel_grouping_outofbounds[0]>", line 1, in <module>
NameError: name 'pha' is not defined
/lagado.real/sherpa/sherpa-xspec/sherpa/astro/tests/test_astro_data.py:1361: UnexpectedException
============================================================================= 1 failed, 485 passed, 7 xfailed in 15.77s =============================================================================
```

So, why is this failing when run individually but isn't when run just as `pytest`?

**Comment by hamogu** [comment]
`sherpa/astro` is blacklisted in `doctest_norecursedirs` (https://github.com/sherpa/sherpa/blob/main/pytest.ini#L11), so when you call pytest in general (without specifying a particular file) doctests in that file are not run. 

However, when doctestplus is installed AND you select a particular file, then it's run on that file and thus it discovers the comment in the docstring of that particular test which is formatted as a doctest (https://github.com/sherpa/sherpa/blob/main/sherpa/astro/tests/test_astro_data.py#L1368) and thus tries to run it.

Now, why does it do that without setting the `--doctest` or `--doctestplus` parameters? That's the question I need to look at and possibly raise in doctestplus.

However, I note that fixing the doctests would also do the trick, e.g. just mark up with `doctest: +SKIP` or `__doctest_skip__ = ['myfunction', 'MyClass', 'MyClass.*']` on the top of the file. That might be easier if it's happening in only a few files; I'm happy to mark them up if we think it's only a small number of files since my long-term goal is to make it work for all files and remove the need to blacklist anything in `doctest_norecursedirs`.

**Comment by DougBurke** [comment]
Ta for the input.
