### ISSUE TITLE
what is load_image doing with the coord argument?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1762]
This is based on helpdesk ticket 024656 handled by @nplee 

In the following, the "log" dataset is behaving as we'd expect. The "phys" dataset claims it's in a physical system but has returned logical coordinates for the independent axis (I would have expected `x0` and `x1` to match the `ll0` and `ll1` arrays, not `l0` and `l1`).

```
sherpa-4.15.0> load_image("phys", "acisf07999_000N001_r0035_regevt3_srcimg.fits", coord="physical")

sherpa-4.15.0> load_image("log", "acisf07999_000N001_r0035_regevt3_srcimg.fits", coord="logical")

sherpa-4.15.0> get_coord("log")
'logical'

sherpa-4.15.0> get_coord("phys")
'physical'

sherpa-4.15.0> l0, l1 = get_indep("log")

sherpa-4.15.0> x0, x1 = get_indep("phys")

sherpa-4.15.0> l0[0:10]
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

sherpa-4.15.0> l1[0:10]
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

sherpa-4.15.0> x0[0:10]
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

sherpa-4.15.0> x1[0:10]
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

sherpa-4.15.0> set_coord("log", "physical")

sherpa-4.15.0> ll0, ll1 = get_indep("log")

sherpa-4.15.0> ll0[0:10]
array([3062.31005859, 3063.31005859, 3064.31005859, 3065.31005859,
       3066.31005859, 3067.31005859, 3068.31005859, 3069.31005859,
       3070.31005859, 3071.31005859])

sherpa-4.15.0> ll1[0:10]
array([4333.12988281, 4333.12988281, 4333.12988281, 4333.12988281,
       4333.12988281, 4333.12988281, 4333.12988281, 4333.12988281,
       4333.12988281, 4333.12988281])
```

It may be intended, but it looks like a bug.

**Comment by DougBurke** [comment]
The current `load_image` docstring can be seen at https://sherpa.readthedocs.io/en/4.15.0/ui/api/sherpa.astro.ui.load_image.html and doesn't add any clarity. It calls

-  https://sherpa.readthedocs.io/en/4.15.0/ui/api/sherpa.astro.ui.unpack_image.htm 

which calls 

- https://sherpa.readthedocs.io/en/4.15.0/overview/api/sherpa.astro.io.read_image.html 

and I'm not sure it really does much with the argument other than checking it exists - e.g.

```
sherpa-4.15.0> load_image(1, "acisf07999_000N001_r0035_regevt3_srcimg.fits", coord="foo")
DataErr: unknown coordinates: 'foo'
```

Given that `get_coord` just returns the `coord` attribute of the `DataIMG` object, I think it likely that the `unpack_image` code just does a

    foo.coord = ....

rather than 

    foo.set_coord(...)

which was recently-ish () shown to be problematic - issue #1380 with a fix in #1414

**Comment by DougBurke** [comment]
Although this doesn't explain it, as you shouldn't be able to change `.coord` directly any more:

```
>>> ui.get_data().coord = "foo"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-master/sherpa/utils/__init__.py", line 171, in __setattr__
    object.__setattr__(self, name, val)
AttributeError: property 'coord' of 'DataIMG' object has no setter
```

So it's likely something to do with setting `coord` in the `DataIMG` initilization:

```python
    def __init__(self, name, x0, x1, y, shape=None, staterror=None,
                 syserror=None, sky=None, eqpos=None, coord='logical',
                 header=None):
        self.sky = sky
        self.eqpos = eqpos
        self._set_coord(coord)
        self.header = {} if header is None else header
        self._region = None

        # Store the original axes so we can always recreate the other
        # systems without having to worry about numerical differences
        # from switching between systems. This is an explicit decision
        # to go for repeatable behavior at the expense of using more
        # memory. See #1380 for more information.
        #
        self._orig_indep_axis = (self.coord, x0, x1)

        super().__init__(name, x0, x1, y, shape, staterror, syserror)
```

**Comment by DougBurke** [comment]
I think I see what the problem is. When you call `DataIMG(name, x0, x1, y, ..., coord=name, ...)` then we are assuming that `x0`/`x1` are in the `name` coordinate system. However, here `x0` and `x1` are in the logical system even when `coord` is not set to `logical`.

There's multiple ways to address this. I think I'm going to go for a local solution rather than try to be clever and "fix" this globally (as there may be times when you want to send in a physical system for the coordinates, although I'm not sure it would make sens to do so given how our coordinate systems work).
