### ISSUE TITLE
doctestplus tests fail when no I/O module is available

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1818]
I'm running tests with a minimal install (no matplotlib or astropy) and they are fine, but if I then do

    pip install -r test_requirements.txt

(which just installs `pytest-doctestplus`) then I get failures from `sherpa/astro/data.py` with errors like

```
_________________________________ [doctest] sherpa.astro.data.DataPHA.sum_background_data _________________________________
3805         to divide by the number of background files used.
3806 
3807         Example
3808         -------
3809 
3810         Calculate the background counts, per channel, scaled to match
3811         the source:
3812 
3813         >>> from sherpa.astro.io import read_pha
3814         >>> pha = read_pha(data_3c273 + '3c273.pi')
UNEXPECTED EXCEPTION: NotImplementedError('No usable I/O backend was imported.')
Traceback (most recent call last):
  File "/lagado2.real/local/anaconda/envs/sherpa-main/lib/python3.11/doctest.py", line 1351, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest sherpa.astro.data.DataPHA.sum_background_data[1]>", line 1, in <module>
  File "/lagado.real/sherpa/sherpa-main/sherpa/astro/io/__init__.py", line 528, in read_pha
    datasets, filename = backend.get_pha_data(arg,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lagado.real/sherpa/sherpa-main/sherpa/astro/io/dummy_backend.py", line 44, in get_table_data
    raise NotImplementedError('No usable I/O backend was imported.')
NotImplementedError: No usable I/O backend was imported.
/lagado.real/sherpa/sherpa-main/sherpa/astro/data.py:3814: UnexpectedException
```

Installing `astropy` fixes this, but it's not ideal. I don't know why this doesn't cause problems for the "minimal" CI runs which do not install `astropy`, as I thought these `doctest` tests were being run on CI.

**Comment by DougBurke** [comment]
Aha - I've now triggered this on CI as part of working on #1816

**Comment by hamogu** [comment]
Well, without a backend, we can't read files. Those examples need to be marked:

See "Doctest dependencies" in https://github.com/scientific-python/pytest-doctestplus
There are several options, e.g. in setup.cfg or in the file where it's used e.g.:

```Python
doctest_subpackage_requires =
    sherpa/astro/data.py = astropy
```

I don't think it supports an "either-or" dependency, but we can e.g. require astropy and make sure that one run uses astropy so that the tests are actually run. Alternatively, we simply run the doctests only once on CI in a run that has all dependencies. I don't think we will recommend that users run the doctests as default, so I don't think that's a problem.

**Comment by DougBurke** [comment]
There's https://github.com/scientific-python/pytest-doctestplus/tree/main#doctest-dependencies but this seems to just gate on whether a module can be imported and not a more-generic check [I'm trying to think of ways to crearte a temporary/hack module which reflects on whether we have the sherpa test data, but it would be hacky at best]

**Comment by hamogu** [comment]
This is similar to https://github.com/astropy/pytest-remotedata except that our data is not on the internet, but in a specific sub-directory. Maybe that can be adapted; I need to think about this more.
