### ISSUE TITLE
HRC RMF doesn't work with AstroPy backend

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1830]
Reported using Sherpa 4.15 but it's present in the current build.

# CIAO 4.15

```
% python doit.py 
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
I/O backend: <module 'sherpa.astro.io.crates_backend' from '/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/io/crates_backend.py'>

read ARF file hrcf02871_001N029_r2824_arf3.fits
read RMF file hrcf02871_001N029_r2824_rmf3.fits
read background file hrcf02871_001N029_r2824_pha3.fits
dataset 1: 0.06:10 -> 0.296667:8.00138 Energy (keV)
Dataset               = 1
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 33.6599
Final fit statistic   = 1.81352 at function evaluation 37
Data points           = 12
Degrees of freedom    = 10
Probability [Q-value] = 0.99758
Reduced statistic     = 0.181352
Change in statistic   = 31.8463
   pl.gamma       -1.08547     +/- 1.95137     
   pl.ampl        1.81415e-05  +/- 4.75439e-05 
```

# CIAO 4.15 with AstroPy backend

```
% grep io_pkg SHERPA-ASTROPY.rc
# io_pkg   : crates pyfits dummy
io_pkg     : pyfits crates
%
% SHERPARC=`pwd`/SHERPA-ASTROPY.rc python doit.py 
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
I/O backend: <module 'sherpa.astro.io.pyfits_backend' from '/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/io/pyfits_backend.py'>

read ARF file hrcf02871_001N029_r2824_arf3.fits
read RMF file hrcf02871_001N029_r2824_rmf3.fits
read background file hrcf02871_001N029_r2824_pha3.fits
dataset 1: 0.06:10 -> 0.296667:8.00138 Energy (keV)
Traceback (most recent call last):
  File "/home/dburke/csc/csc21/hrc_flux/csc21/doit.py", line 15, in <module>
    ui.fit()
  File "<string>", line 1, in fit
  File "/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/ui/utils.py", line 10256, in fit
    self._fit(id, *otherids, **kwargs)
  File "/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/ui/utils.py", line 10364, in _fit
    res = f.fit(**kwargs)
  File "/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/fit.py", line 55, in run
    fit.model.startup(cache=cache)
  File "/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/instrument.py", line 542, in startup
    _notice_resp(self.pha.get_noticed_channels(), self.arf, self.rmf)
  File "/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/data.py", line 182, in _notice_resp
    bin_mask = rmf.notice(chans)
  File "/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/data.py", line 1262, in notice
    bin_mask) = filter_resp(noticed_chans, self.n_grp, self.f_chan,
TypeError: response filter failed
```

Files can be accessed from

[csc21.zip](https://github.com/sherpa/sherpa/files/12187716/csc21.zip)

**Comment by DougBurke** [comment]
Using the CIAO 4.15 environment we can see that pyfits_backend creates a rather-different structure than crates:

```
sherpa In [1]: rmf1 = unpack_rmf("csc21/hrcf02871_001N029_r2824_rmf3.fits.gz")

sherpa In [2]: from sherpa.astro import io

sherpa In [3]: io.backend
Out[3]: <module 'sherpa.astro.io.crates_backend' from '/home/dburke/micromamba/envs/ciao415/lib/python3.10/site-packages/sherpa/astro/io/crates_backend.py'>

sherpa In [4]: from sherpa.astro.io import pyfits_backend

sherpa In [5]: io.backend = pyfits_backend

sherpa In [6]: rmf2 = unpack_rmf("csc21/hrcf02871_001N029_r2824_rmf3.fits.gz")

sherpa In [7]: print(rmf1)
name     = csc21/hrcf02871_001N029_r2824_rmf3.fits.gz
energ_lo = Float64[16921]
energ_hi = Float64[16921]
n_grp    = UInt64[16921]
f_chan   = UInt32[16960]
n_chan   = UInt32[16960]
matrix   = Float64[8525597]
e_min    = Float64[1024]
e_max    = Float64[1024]
detchans = 1024
offset   = 1
ethresh  = 1e-10

sherpa In [8]: print(rmf2)
name     = csc21/hrcf02871_001N029_r2824_rmf3.fits.gz
energ_lo = Float64[16921]
energ_hi = Float64[16921]
n_grp    = UInt64[16921]
f_chan   = UInt64[50763]
n_chan   = UInt64[50763]
matrix   = Float64[8798920]
e_min    = Float64[1024]
e_max    = Float64[1024]
detchans = 1024
offset   = 1
ethresh  = 1e-10
```

**Comment by DougBurke** [comment]
So, when reading the matrix it ends up triggering the `isinstance(data['matrix'], _VLF)` check, which means there's no loop through tweaking the `f_chan` or `n_chan` arrays. I've never understood this section as it is woefully lacking in documentation, so it's not immediately obvious what to do...

https://github.com/sherpa/sherpa/blob/ddab8abbdf8a9d2ade4854281229b03199fbc3cf/sherpa/astro/io/pyfits_backend.py#L731-L783

**Comment by DougBurke** [comment]
I think this is me just finding a bug @hamogu reported many moons ago: #1344
