### ISSUE TITLE
ignore_bad issues

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1936]
This is probably just #1169 but it may be subtly different (and the surrounding code behaviour has changed since this time so I want to just note what I found and we can worry about how they are related later):

With the CIAO 4.16 branch

```
sherpa-4.16.0> load_pha("9774.pi")
read ARF file 9774.arf
read RMF file 9774.rmf
read background file 9774_bg.pi

sherpa-4.16.0> notice(0.4, 8)
dataset 1: 0.00146:14.9504 -> 0.3942:8.0008 Energy (keV)

sherpa-4.16.0> group_counts(20)
dataset 1: 0.3942:8.0008 Energy (keV) (unchanged)
```

As noted in #1935 we don't have a good way to note if we have any "bad" data to ignore, but we can do it manually

```
sherpa-4.16.0> (get_quality() > 0).any()
True
```

So, what happens if I call `ignore_bad`?

```
sherpa-4.16.0> ignore_bad()
WARNING: filtering grouped data with quality flags, previous filters deleted
dataset 1: 0.3942:8.0008 -> 0.00146:14.9504 Energy (keV)
```

This is **INCREDIBLY ANNOYING** (even though I know, or at least used to know, why it did this; I'm hoping we no-longer need to do this but it requires research which I do not have time to do).

Also **NOTE** that the `dataset 1: ...` line makes no note of the quality-ignored bins, which is not great...

Okay, I'm going to re-apply the selected filter of 0.4 to 8 to see what happens

```
sherpa-4.16.0> notice(0.4, 8)

```

Errr, why is there no screen output? Probably because the code is falling over and just hiding this fact, since trying to get the filter directly errors out:

```
sherpa-4.16.0> get_filter()
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1024 but corresponding boolean dimension is 970
```

I had hoped the filter work I've been doing would have fixed all this but obviously not.

**Comment by DougBurke** [comment]
We do have a test dataset we can use (found when working on #2118) -

`sherpa-test-data/sherpatest/sis0_mar24_bin.pha`

```
% dmlist s0_mar24_bin.pha"[cols -sys_err][#row=:24]" data,clean
#  CHANNEL COUNTS     QUALITY    GROUPING
      0          0          0          1
      1          0          5         -1
      2          0          5         -1
      3          0          5         -1
      4          0          5         -1
      5          0          5         -1
      6          0          5         -1
      7          0          5         -1
      8          0          5         -1
      9          0          5         -1
     10          0          5         -1
     11          0          5         -1
     12          0          5         -1
     13          0          5         -1
     14         13          5         -1
     15         15          5         -1
     16          8          5         -1
     17         17          0         -1
     18         12          0          1
     19          9          0         -1
     20          7          0          1
     21         12          0         -1
     22         18          0          1
     23         15          0          1
```

The `QUALITY=5` rows are "never seen" by XSPEC users - see `Within XSPEC, Qual=1 and Qual=5 rows will never be accessible and Qual=2 may be ignored using the “ignore bad" command.` from https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node7.html and I can confirm that Sherpa and XSPEC do behave subtly different with this data...

**Comment by DougBurke** [comment]
Also

```
% dmlist xrbg_xspec.pi"[spectrum][quality!=0][cols -channel]" data,clean  | uniq
#  RATE                 STAT_ERR             QUALITY    GROUPING
                    0                    0          2          1
                    0                    0          2         -1
                    0                    0          2          0
```

**Comment by DougBurke** [comment]
With #2161 we at least now provide some information to the user:

```
>>> from sherpa.astro.ui import *
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> load_pha("sherpa-test-data/sherpatest/9774.pi")
read ARF file sherpa-test-data/sherpatest/9774.arf
read RMF file sherpa-test-data/sherpatest/9774.rmf
read background file sherpa-test-data/sherpatest/9774_bg.pi
>>> notice(0.4, 8)
dataset 1: 0.00146:14.9504 -> 0.3942:8.0008 Energy (keV)
>>> group_counts(20)
dataset 1: 0.3942:8.0008 Energy (keV) (unchanged)
>>> (get_quality() > 0).any()
True
>>> ignore_bad()
WARNING: filtering grouped data with quality flags, previous filters deleted
dataset 1: 0.3942:8.0008 -> 0.00146:14.9504 Energy (keV)
>>> notice(0.4, 8)
ERROR: dataset 1: 1D filter has failed
>>> get_filter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in get_filter
  File "/lagado.real/sherpa/sherpa-1/sherpa/ui/utils.py", line 4176, in get_filter
    return self.get_data(id).get_filter(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lagado.real/sherpa/sherpa-1/sherpa/astro/data.py", line 4909, in get_filter
    return create_expr_integrated(xlo[mask], xhi[mask], mask=mask, format=format, delim=delim)
                                  ~~~^^^^^^
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1024 but corresponding boolean dimension is 970
>>> notice()
dataset 1: <broken> -> 0.00146:14.9504 Energy (keV)
>>> get_filter()
'0.001460000058:14.950400352478'
```
