### ISSUE TITLE
data validation for DataPHA is missing some corner cases

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1995]
Found from adding typing rules (the error was that `mypy` noted that `len(self.channel)` was not guarded by a "but you may not have data" check):
```
% python
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sherpa.astro.ui import *
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> rmf = unpack_rmf("sherpa-test-data/sherpatest/3c273.rmf")
>>> type(rmf)
<class 'sherpa.astro.instrument.RMF1D'>
>>> rmf._rmf
<DataRMF data set instance 'sherpa-test-data/sherpatest/3c273.rmf'>
>>> actual = rmf._rmf
>>> pha = DataPHA("X", None, None)
>>> pha.set_response(rmf=actual)
>>> pha.set_analysis("energy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lagado.real/sherpa/sherpa-temp/sherpa/astro/data.py", line 2068, in set_analysis
    if rmf is not None and rmf.detchans != len(self.channel):
                                           ^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
>>> 
```

This comes about because we allow the `DataPHA` object to start off unsized and we don't catch this case in `set_analysis`.

This is not a high-priority bug!

**Comment by DougBurke** [comment]
I had hoped I'd caught this with one of

- #2118
- #2123 
- #2147 

but no luck! I should have written a test for this case ...
