### ISSUE TITLE
can not use spawn or forkserver methods for multiprocessing

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#2007]
[**EDITED TO ADD** I do not know why GitHub thinks #2243 will fix this as it will not]

This is fallout from looking into #1015 but is not related to it (that is, it is not an issue for #2006, or - rather - that PR doesn't change the existing behaviour).

1. we explicitly do not support the `forkserver` method (an easy fix)
2. using `spawn` (and probably `forkserver` but I haven't checked) we get errors because 
    - we need to handle callbacks differently since we can't pickle the local callback routines that we use with the `fork` method
    - likely the same issue, but we need to take more care about sharing information between the process and the parent

As an example, with CIAO 4.16:

# the default fork method

This errors out as expected

```
>>> from sherpa.utils import parallel
>>> parallel.multiprocessing_start_method
'fork'
>>> def func(x):
...     if x == 2:
...         raise ValueError("x")
...     return x ** 2
... 
>>> parallel.parallel_map(func, [1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py", line 397, in parallel_map
    return run_tasks(procs, err_q, out_q)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py", line 264, in run_tasks
    process_tasks(procs, err_q)
  File "/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py", line 230, in process_tasks
    raise err_q.get()
ValueError: x
```

# with `spawn`

```
>>> from sherpa.utils import parallel
>>> parallel.multiprocessing_start_method
'spawn'
>>> def func(x):
...     if x == 2:
...         raise ValueError("x")
...     return x ** 2
... 
>>> parallel.parallel_map(func, [1, 2, 3])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/soft/ciao-4.16/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/soft/ciao-4.16/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'func' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/soft/ciao-4.16/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/soft/ciao-4.16/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'func' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/soft/ciao-4.16/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/soft/ciao-4.16/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'func' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py", line 397, in parallel_map
    return run_tasks(procs, err_q, out_q)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py", line 278, in run_tasks
    vals.extend(r)
TypeError: 'NoneType' object is not iterable
```

The error handling doesn't provide any useful information because of pickle problems.

If you run our tests you also get a lot of problems because of this - here is an example

```
/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py:397: in parallel_map
    return run_tasks(procs, err_q, out_q)
/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py:264: in run_tasks
    process_tasks(procs, err_q)
/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/parallel.py:218: in process_tasks
    proc.start()
/soft/ciao-4.16/lib/python3.11/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
/soft/ciao-4.16/lib/python3.11/multiprocessing/context.py:224: in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
/soft/ciao-4.16/lib/python3.11/multiprocessing/context.py:288: in _Popen
    return Popen(process_obj)
/soft/ciao-4.16/lib/python3.11/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/soft/ciao-4.16/lib/python3.11/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/soft/ciao-4.16/lib/python3.11/multiprocessing/popen_spawn_posix.py:47: in _launch
    reduction.dump(process_obj, fp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <Process name='Process-2574' parent=1198314 initial>
file = <_io.BytesIO object at 0x7f11b900a5c0>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'test_parallel_map_on_error.<locals>.func'

/soft/ciao-4.16/lib/python3.11/multiprocessing/reduction.py:60: AttributeError
```

**Comment by DougBurke** [comment]
I do have some code based on #2006 to address this but it's a slow slog going through checking things.

**Comment by DougBurke** [comment]
See also https://github.com/python/cpython/issues/125714

**Comment by DougBurke** [comment]
Note that #2243 did not close this issue.
