### ISSUE TITLE
Shold we replace `NoNewAttributesAfterInit` with `__slots__`

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#2008]
So, we can change

```python
from sherpa.utils import NoNewAttributesAfterInit

class Foo(NoNewAttributesAfterInit):
    def __init__(self, a):
        self.a = a
        super().__init__()

class Bar(Foo):
    pass

class Bax(Bar):
    def __init__(self, a, b):
        self.b = b
        super().__init__(a)
```

with

```
class Foo:

    __slots__ = ("a", )

    def __init__(self, a):
        self.a = a

class Bar(Foo):

    __slots__ = ()

class Bax(Bar):

    __slots__ = ("b", )

    def __init__(self, a, b):
        self.b = b
        super().__init__(a)
```

Both give the same "positive" behavior:

```
>>> a = Foo("a")
>>> b = Bar("b")
>>> c = Bax("c", "d")
>>> a.a
'a'
>>> b.a
'b'
>>> c.a
'c'
>>> c.b
'd'
```

The error when you try to access or create an invalid attribute is similar. 

- with NoNewAttributesAfterInit

```
>>> c.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bax' object has no attribute 'x'
>>> c.x = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/soft/ciao-4.16/lib/python3.11/site-packages/sherpa/utils/__init__.py", line 118, in __setattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Bax' object has no attribute 'x'
```

- with slots

```
>>> c.x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bax' object has no attribute 'x'
>>> c.x = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bax' object has no attribute 'x'
```

So the error is essentially the same, it's just the traceback that may be a little different.

So

# Reasons for doing

- it should reduce memory (not checked, and not what I care about)
- it would remove some code from `sherpa.utils`
- more idiomatic Python (in some quarters)

# Reasons for not doing

- this code is well tested and is unlikely going to need changes in the future (given how attributes are handled)
- why change code that works as the "slotted" version does not really add any new capabilities (if we do not care about memory use)
- it would make whatever version of Sherpa we do it in a "flag day" in that the output of `sherpa.ui.save` could not be used with older versions of Sherpa (and vice versa)
  - however, we don't make any guarantees about this property and this issue has happened before
- when using slots we would need to make sure we always set `__slots__`, even for classes that add nothing (e.g. the `Bar` class above) otherwise they would accidentally gain the ability to add new fields/attributes
- we can't define class attributes that are not fixed - they always have to be defined in `__init__` calls, which is mainly code churn but does mean we lose the ability to add docstrings to them (mainly visible in the RTD pages)

If we do it we don't actually need to do it all in one - it can be done on a per-class hierarchy system as we decide to (e.g. working on changes to a particular set of classes).

**Comment by hamogu** [comment]
Interesting idea. It's one of those things that does not quite seem worth the effort right now, and probably never will at any particular point but that might be good to have in the long run. `__slots__` are also supposed to be faster (I agree that we don't care about the memory). I suspect that it's not enough to matter but if we get that for free from a change we might do for other reasons anyway, I'd take that.

From Python 3.10+, there is also the [decorator `dataclass.dataclass(slots=True)`](https://github.com/sherpa/sherpa/issues/787) with that, code might get even simpler for those classes that we might want to turn into dataclasses as discussed in #787. I closed that because, like here, it seemed like a reasonable idea, but not worth the effort. However, we now have a few dataclasses in Sherpa and there are more cases with might want to use them (for example, all out `Data1D`, `Data1DInt`... might profit from that all the way up to specialized cases like `DataRMF`).

Maybe it's worth exploring to do both (slots and turn more classes in to dataclasses to reduce boilerplate code) at the same time. However, we might want to wait until we drop 3.9 to be able to take advantage of both at the same time.
