### ISSUE TITLE
Read in of PHA files has regressed

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#2117]
**DOH** some of this is because `sherpa.astro.io.write_pha` defaults to `ascii=True`, for some reason. So the block name check will fail and the column types will be wrong.

With CIAO 4.16 I get

```
sherpa-4.16.0> pha = unpack_pha("/lagado.real/sherpa/sherpa-test-data/sherpatest/3c273.pi", use_errors=True)
read ARF file /lagado.real/sherpa/sherpa-test-data/sherpatest/3c273.arf
read RMF file /lagado.real/sherpa/sherpa-test-data/sherpatest/3c273.rmf
read background file /lagado.real/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi

sherpa-4.16.0> pha.staterror.sum()
449.715938307728

sherpa-4.16.0> from sherpa.astro import io

sherpa-4.16.0> io.write_pha("delme.pi", pha)

sherpa-4.16.0> !dmlist delme.pi cols
 
--------------------------------------------------------------------------------
Columns for Table Block delme.pi
--------------------------------------------------------------------------------
 
ColNo  Name                 Unit        Type             Range
   1   CHANNEL                           Real8          -Inf:+Inf            
   2   COUNTS                            Real8          -Inf:+Inf            
   3   STAT_ERR                          Real8          -Inf:+Inf            
   4   GROUPING                          Real8          -Inf:+Inf            

sherpa-4.16.0> !dmstat delme.pi"[cols stat_err]" sig-
STAT_ERR
    min:	0 	      @:	1 
    max:	3.1622776602 	      @:	52 
   mean:	0.439175721 
    sum:	449.71593831 
   good:	1024 
   null:	0 
```

The last check is to make sure STAT_ERR is written out correctly.

```
sherpa-4.16.0> !dmlist delme.pi blocks
 
--------------------------------------------------------------------------------
Dataset: delme.pi
--------------------------------------------------------------------------------
 
     Block Name                          Type         Dimensions
--------------------------------------------------------------------------------
Block    1: delme.pi                       Table         4 cols x 1024     rows

sherpa-4.16.0> pha2 = unpack_pha("delme.pi", use_errors=True)
RuntimeError: dmDatasetGetBlock() failed to open block 2.
```

This is because the block name should be called SPECTRUM, I think. Also, the GROUPING column is written out as a float and not an integer.

If I use the development branch then I see different, but related, issues, so #1921 didn't fix all these issues.

**Comment by DougBurke** [comment]
I'm closing this as I think  I just got stupidly confused.

**Comment by DougBurke** [comment]
**AHA** I have found an issue:

With 4.16.0 I could (in `sherpa-test-data/sherpatest/`):

```
sherpa In [1]: load_pha("s0_mar24_bin.pha")
systematic errors were found in file 's0_mar24_bin.pha' 
but not used; to use them, re-read with use_errors=True
read ARF file s0_mar24.arf
read RMF file s0_mar24.rmf
WARNING: File s0_bkg_sky.pha does not exist.

sherpa In [2]: load_pha("s0_mar24_bin.pha", use_errors=True)
read ARF file s0_mar24.arf
read RMF file s0_mar24.rmf
WARNING: File s0_bkg_sky.pha does not exist.
sherpa In [4]: print(pha)
name           = s0_mar24_bin.pha
channel        = Float64[512]
counts         = Float64[512]
staterror      = None
syserror       = Float32[512]
bin_lo         = None
bin_hi         = None
grouping       = Int16[512]
quality        = Int16[512]
exposure       = 33483.25
backscal       = 0.044189453125
areascal       = 1.0
grouped        = True
subtracted     = False
units          = energy
rate           = True
plot_fac       = 0
response_ids   = [1]
background_ids = []

```

but I now can not

```
>>> from sherpa.astro import ui
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
>>> ui.load_pha("sherpa-test-data/sherpatest/s0_mar24_bin.pha")
statistical and systematic errors were found in file 'sherpa-test-data/sherpatest/s0_mar24_bin.pha'
but not used; to use them, re-read with use_errors=True
read ARF file sherpa-test-data/sherpatest/s0_mar24.arf
read RMF file sherpa-test-data/sherpatest/s0_mar24.rmf
WARNING: unable to read background: file 'sherpa-test-data/sherpatest/s0_bkg_sky.pha' not found
>>> ui.load_pha("sherpa-test-data/sherpatest/s0_mar24_bin.pha", use_errors=True)
read ARF file sherpa-test-data/sherpatest/s0_mar24.arf
read RMF file sherpa-test-data/sherpatest/s0_mar24.rmf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in load_pha
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/ui/utils.py", line 2356, in load_pha
    phasets = self.unpack_pha(arg, use_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/ui/utils.py", line 2159, in unpack_pha
    return sherpa.astro.io.read_pha(arg, use_errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/__init__.py", line 1044, in read_pha
    data = _process_pha_block(filename, p,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/__init__.py", line 843, in _process_pha_block
    pha = DataPHA(filename, counts=get("COUNTS"),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/data.py", line 1736, in __init__
    super().__init__(name, channel, counts, staterror, syserror)
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/data.py", line 1693, in __init__
    super().__init__(name, (x, ), y, staterror, syserror)
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/data.py", line 879, in __init__
    self.staterror = staterror
    ^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/utils/__init__.py", line 142, in __setattr__
    object.__setattr__(self, name, val)
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/data.py", line 1276, in staterror
    self._set_related("staterror", val)
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/data.py", line 1756, in _set_related
    raise DataErr("notanarray")
sherpa.utils.err.DataErr: Array must be a sequence or None
```

Is it because the `STAT_ERR` is a scalar (and 0) but `SYS_ERR` is set?

```
% dmlist s0_mar24_bin.pha cols
 
--------------------------------------------------------------------------------
Columns for Table Block SPECTRUM
--------------------------------------------------------------------------------
 
ColNo  Name                 Unit        Type             Range
   1   CHANNEL                           Int2           0:511                label for field   1
   2   COUNTS               count        Int4           -                    label for field   2
   3   SYS_ERR                           Real4          -Inf:+Inf            label for field   3
   4   QUALITY                           Int2           -                    label for field   4
   5   GROUPING                          Int2           -                    label for field   5
% dmlist s0_mar24_bin.pha header,clean,raw | grep ERR
TTYPE3       = SYS_ERR              / label for field   3 
POISSERR     = T                    / Poissonian errors to be assumed
STAT_ERR     = 0                    / no statistical error specified
```
