### ISSUE TITLE
No longer build the stk and group library?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#2159]
I have the latest main branch and after building Sherpa I get

```
% python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sherpa.astro.ui import *
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: the group module (from the CIAO tools package) is not installed.
Dynamic grouping functions will not be available.
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> import stk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```

So, it looks like #1949 has broken things (this would be my guess when it happened).

**Comment by DougBurke** [comment]
This was with

    pip install -e .

If I

    pip install .

it does seem to work. Investigating.

**Comment by DougBurke** [comment]
So,

```
% pip install -e .
...
% find . -name stk.so
./extern/stklib-4.11/src/.libs/stk.so
./build/lib/python3.11/site-packages/stk.so
./stk.so
% python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stk
>>> from sherpa.astro.ui import *
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> 
```

but if I change directory we lose it

```
% pushd sherpa-test-data/sherpatest/
python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'stk'
>>> from sherpa.astro.ui import *
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: the group module (from the CIAO tools package) is not installed.
Dynamic grouping functions will not be available.
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> 
```

So, I assune it's related to how editable installs get "added into" the `PYTHONPATH` (or whatever it's called) environment.

**Comment by DougBurke** [comment]
So, it's an annoyance for developers, but can be worked around. I wonder if #2096 would magically solve it.

**Comment by Marie-Terrell** [comment]
I can reproduce this as well. Previously (sherpa dir and .):
```
lib/python3.11/site-packages/sherpa.egg-link
```
Swapped to:
```
lib/python3.11/site-packages/__editable__.sherpa-4.16.1+357.gfd5f810d.pth
lib/python3.11/site-packages/__editable___sherpa_4_16_1_357_gfd5f810d_finder.py
```
Where the second file lists the mapping and namespace to pick up (does not include stk). Going into the dir (like you did) or adding the "/path-to-sherpa-clone/build/lib/python3.11/site-packages" to the PYTHONPATH picks it up.

I had previously done my checks of the editable install in the sherpa dir, so I didn't see the issue.

**Comment by DougBurke** [comment]
Yeah - I don't think it's as worrying as I at first thought.

**Comment by DougBurke** [comment]
I **think** the `src/` build approach - e.g. #2096 - works since

```
>>> pip install -e .
....
>>> find . -name stk.so
./extern/stklib-4.11/src/.libs/stk.so
./build/lib/python3.11/site-packages/stk.so
./src/stk.so
>>> pwd
/home/dburke/sherpa/sherpa-2
>>> find $CONDA_PREFIX -name \*pth
/home/dburke/micromamba/envs/sherpa-2/lib/python3.11/site-packages/easy-install.pth
/home/dburke/micromamba/envs/sherpa-2/lib/python3.11/site-packages/distutils-precedence.pth
/home/dburke/micromamba/envs/sherpa-2/lib/python3.11/site-packages/__editable__.sherpa-4.16.1+366.gb879751a.dirty.pth
>>> cat /home/dburke/micromamba/envs/sherpa-2/lib/python3.11/site-packages/__editable__.sherpa-4.16.1+366.gb879751a.dirty.pth
/home/dburke/sherpa/sherpa-2/src
```

So it means you don't have to mess with PYTHONPATH - e.g.

```
% pushd /tmp
% python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sherpa
>>> sherpa.__file__
'/home/dburke/sherpa/sherpa-2/src/sherpa/__init__.py'
>>> import stk
>>> stk.__file__
'/home/dburke/sherpa/sherpa-2/src/stk.so'
>>> from sherpa.astro import ui
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
>>> ui.__file__
'/home/dburke/sherpa/sherpa-2/src/sherpa/astro/ui/__init__.py'
```
