### ISSUE TITLE
Issues using wstat when grouping/filtering data

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#227]
I was just grouping/filtering for plotting of the results of fitting using `wstat`. The arrays get confused and  I get errors. See below. This should be seen for standard X-ray PHA files and analysis. I used CSC1 data set here.

```
load_data('acisf06114_000N002_r0025_pha3.fits.gz')
set_model('xsphabs.abs1*powlaw1d.p1')
set_method('simplex')
set_stat('wstat')
notice(0.5,7.)
fit()

group_counts(10)
subtract()
#plot_fit()

fit() # correct error
unsubtract()
fit() # Array size mismatch
```

Here is the screen output with the error:

>   File "/soft/ciao-4.8/ots/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3032, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-13-749b6e6de45a>", line 1, in <module>
>     fit()
>   File "<string>", line 1, in fit
>   File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", line 9259, in fit
>     self._fit(id, _otherids, *_kwargs)
>   File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", line 9363, in _fit
>     res = f.fit(*_kwargs)
>   File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/fit.py", line 58, in run
>     result = func(fit, *args, *_kwargs)
>   File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/fit.py", line 1106, in fit
>     init_stat = self.calc_stat()
>   File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/fit.py", line 1020, in calc_stat
>     bkg=bkg_data)[0]
>   File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/stats/__init__.py", line 601, in calc_stat
>     truncation_value)
> TypeError: statistic input array sizes do not match

**Comment by DougBurke** [comment]
On a related note (found when trying some variations of this bug), should `calc_stat` fail with an error on subtracted data - i.e. in the following `fit` errors out but `calc_stat` does not.

```
% python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from sherpa.astro import ui
>>> ui.load_pha(1, 'sherpa-test-data/sherpatest/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file sherpa-test-data/sherpatest/3c273.arf
read RMF file sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file sherpa-test-data/sherpatest/3c273_bg.pi
>>> ui.set_source(ui.powlaw1d.pl)
>>> ui.set_stat('wstat')
>>> ui.calc_stat()
15613619.46448725
>>> ui.subtract()
>>> ui.calc_stat()
15614106.603369107
>>> ui.fit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in fit
  File "sherpa/astro/ui/utils.py", line 9262, in fit
    self._fit(id, *otherids, **kwargs)
  File "sherpa/astro/ui/utils.py", line 9366, in _fit
    res = f.fit(**kwargs)
  File "sherpa/fit.py", line 60, in run
    result = func(fit, *args, **kwargs)
  File "sherpa/fit.py", line 1108, in fit
    raise FitErr('statnotforbackgsub', self.stat.name)
sherpa.utils.err.FitErr: wstat statistics cannot be used with background subtracted data
>>> 
```

**Comment by DougBurke** [comment]
I think the problem that @anetasie  reported is actually due to the behavior of `group_counts`. I can understand the current behavior, and am not sure what is the best solution. First, a simplified version of the original test case [note, I have not guaranteed that there aren't problems with subtract/unsubtract or filtering, but I am going to leave those for the tests in #267 and any code that fixes them].

# Simplified test case

```
% python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from sherpa.astro import ui
>>> ui.load_data('sherpa-test-data/sherpatest/acisf01575_001N001_r0085_pha3.fits.gz')
read ARF file sherpa-test-data/sherpatest/acisf01575_001N001_r0085_arf3.fits
read RMF file sherpa-test-data/sherpatest/acisf01575_001N001_r0085_rmf3.fits
read background file sherpa-test-data/sherpatest/acisf01575_001N001_r0085_pha3.fits
>>> ui.set_source(ui.powlaw1d.pl)
>>> ui.set_stat('wstat')
>>> ui.calc_stat()
89412025.18951344
>>> ui.group_counts(10)
>>> ui.calc_stat()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in calc_stat
  File "sherpa/ui/utils.py", line 7870, in calc_stat
    return f.calc_stat()
  File "sherpa/fit.py", line 1028, in calc_stat
    return self._calc_stat()[0]
  File "sherpa/fit.py", line 1005, in _calc_stat
    bkg=bkg_data)
  File "sherpa/stats/__init__.py", line 601, in calc_stat
    truncation_value)
TypeError: statistic input array sizes do not match
>>> 
```

# Explanation

The issue here is that `group_counts` has grouped the source into 10-count bins and the backgronud into 10-count bins, but they are not the same bins (unless the background counts happened to exactly match the source ones, but that is not a common occurrence). As an example (in the same session as above).

```
>>> (ui.get_grouping(1) == ui.get_grouping(1, bkg_id=1)).all()
False
```

Since the grouping between the source and backgronud is not the same, the wstat calculation fails.

# A work around

The source grouping can be applied to the background dataset, and then wstat will work:

```
>>> ui.set_grouping(1, ui.get_grouping(1), bkg_id=1)
>>> ui.calc_stat()
89411536.85400726
```

# Other possible solutions

If I am going to fit both the source and background datasets (rather than subtract them explicitly or use wstat) then I may well want different grouping bins; that is, the current `group_counts` behaviour is not necessarily wrong.

On the other hand, Sherpa has some "useful, but perhaps illogical" conventions that help out the common case and that can cause confusion as they do here. For instance, if the source PHA file has grouping information in it, but the background does not, then a `load_pha` call will copy over the grouping to the background.

One thought I have is that the `group*` family of commands could have a flag which determines whether they treat the source and background data separately (as they currently do), or if they "ignore" the  background data and just copy over the grouping from the source data. This is somewhat tricky to specify because

- we already have the `id` and `bkg_id` arguments, so need to work out the various cases (i.e. does one argument override the other or do we error out if multiple potentially conflicting parameters are given)

- what is the default behaviour: the current one, or do we feel like the common case is actually going to be "copy over the background grouping"

- for complicated cases (e.g. data sets with multiple background files) can we copy over the source grouping, or are there technical limitations there?

An alternative approach would be for the dataset and/or statistic code to recognize when wstat is in use and for it to just apply the source grouping to the background dataset.

**Comment by DougBurke** [comment]
PR #269 may fix this, but I'm not sure if there are other parts of the system that need updating (and whether the way 269 fixes this is the correct thing to do).

**Comment by DougBurke** [comment]
The initial error reported by @anetasie no longer happens with PR #287 - e.g.

```
In [1]: from sherpa.astro.ui import *

In [2]: cd /home/djburke/data/csc/sherpa/6114/CXOJ140324.1+541948
/home/djburke/data/csc/sherpa/6114/CXOJ140324.1+541948

In [3]: ls
acisf06114_000N002_r0025_arf3.fits.gz  acisf06114_000N002_r0025_rmf3.fits.gz
acisf06114_000N002_r0025_pha3.fits.gz

In [4]: load_pha('acisf06114_000N002_r0025_pha3.fits.gz')
read ARF file acisf06114_000N002_r0025_arf3.fits
read RMF file acisf06114_000N002_r0025_rmf3.fits
read background file acisf06114_000N002_r0025_pha3.fits

In [5]: plot_data()

In [6]: set_model('xsphabs.abs1*powlaw1d.p1')
   ...: set_method('simplex')
   ...: set_stat('wstat')
   ...: notice(0.5,7.)
   ...: 

In [7]: plot_data()
WARNING: The displayed errorbars have been supplied with the data or calculated using chi2xspecvar; the errors are not used in fits with wstat

In [8]: fit()
Dataset               = 1
Method                = neldermead
Statistic             = wstat
Initial fit statistic = 6.87815e+07
Final fit statistic   = 401.006 at function evaluation 631
Data points           = 446
Degrees of freedom    = 443
Probability [Q-value] = 0.92442
Reduced statistic     = 0.905206
Change in statistic   = 6.87811e+07
   abs1.nH        0.497965    
   p1.gamma       1.64551     
   p1.ampl        1.79516e-05 

In [9]: plot_fit()
WARNING: The displayed errorbars have been supplied with the data or calculated using chi2xspecvar; the errors are not used in fits with wstat

In [10]: group_counts(10)

In [11]: subtract()

In [12]: fit()
---------------------------------------------------------------------------
FitErr                                    Traceback (most recent call last)
<ipython-input-12-749b6e6de45a> in <module>()
----> 1 fit()

<string> in fit(id, *otherids, **kwargs)

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/astro/ui/utils.py in fit(self, id, *otherids, **kwargs)
   9260         """
   9261         kwargs['bkg_only'] = False
-> 9262         self._fit(id, *otherids, **kwargs)
   9263 
   9264     def fit_bkg(self, id=None, *otherids, **kwargs):

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/astro/ui/utils.py in _fit(self, id, *otherids, **kwargs)
   9364                     i).mask & numpy.isfinite(self.get_data(i).get_x())
   9365 
-> 9366         res = f.fit(**kwargs)
   9367         res.datasets = ids
   9368         self._fit_results = res

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/fit.py in run(fit, *args, **kwargs)
     49     def run(fit, *args, **kwargs):
     50         fit.model.startup()
---> 51         result = func(fit, *args, **kwargs)
     52         fit.model.teardown()
     53         return result

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/fit.py in fit(self, outfile, clobber)
   1079             raise FitErr('binhas0')
   1080 
-> 1081         init_stat = self.calc_stat()
   1082         # output = self.method.fit ...
   1083         output = self._iterfit.fit(self._iterfit._get_callback(outfile, clobber),

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/fit.py in calc_stat(self)
    994         """
    995 
--> 996         return self._calc_stat()[0]
    997 
    998     def calc_chisqr(self):

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/fit.py in _calc_stat(self)
    975         # TODO: is there anything missing here that
    976         #       self._iterfit.get_extra_args calculates?
--> 977         return self.stat.calc_stat(self.data, self.model)
    978 
    979     def calc_stat(self):

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/stats/__init__.py in calc_stat(self, data, model)
    807     def calc_stat(self, data, model):
    808 
--> 809         data, model = self._validate_inputs(data, model)
    810 
    811         # Need access to backscal values and background data filtered

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/stats/__init__.py in _validate_inputs(self, data, model)
    276     def _validate_inputs(self, data, model):
    277         data, model = Stat._validate_inputs(self, data, model)
--> 278         self._check_background_subtraction(data)
    279         return data, model
    280 

/home/djburke/sherpa/sherpa-rewrite-stat/sherpa/stats/__init__.py in _check_background_subtraction(self, data)
    272                 # (October 2016).
    273                 #
--> 274                 raise FitErr('statnotforbackgsub', self.name)
    275 
    276     def _validate_inputs(self, data, model):

FitErr: wstat statistics cannot be used with background subtracted data

In [13]: unsubtract()

```

Note that the following command does not error out:

```
In [14]: fit()
Dataset               = 1
Method                = neldermead
Statistic             = wstat
Initial fit statistic = 34.8726
Final fit statistic   = 34.8174 at function evaluation 470
Data points           = 44
Degrees of freedom    = 41
Probability [Q-value] = 0.740788
Reduced statistic     = 0.849205
Change in statistic   = 0.0551609
   abs1.nH        0.491417    
   p1.gamma       1.6546      
   p1.ampl        1.79673e-05 

In [15]: plot_fit()
WARNING: The displayed errorbars have been supplied with the data or calculated using chi2xspecvar; the errors are not used in fits with wstat
```
