### ISSUE TITLE
ignore_bad() filter issues with models (Nick's bug)

### ISSUE THREAD

**Issue by jbudynk** [sherpa/sherpa#234]
# Description

The user extracted the spectrum with specextract, then used FTools' GRPPHA to bin the spectrum to at least five counts per bin and flag specific channels as bad (1-35,501-1024). 

Simplifying the steps taken: 

```
load_pha("18076_bin5.pi") 
rmf = get_rmf() 
arf = get_arf() 
bkg_scale = get_bkg_scale() 
set_full_model(rmf(arf(xswabs.abs1*xszwabs.abs2*powlaw1d.pl1)))+bkg_scale*rmf(arf(xswabs.bkgabs*(xsapec.bkgapec))+(powlaw1d.bkgpl+xsgaussian.bkgg1+xsgaussian.bkgg2)))) 
ignore_bad() 
fit() 
*** 
WARNING: data set 1 has associated backgrounds, but they have not been 
subtracted, nor have background models been set 
ValueError: shape mismatch between 'ARFModelPHA: 1070' and 'BinaryOpModel: 
1063' 
***
```

throws an error. I'm pretty sure it has to do with the 'bkg_scale' component of the model, where the APEC component is convolved with the response while the power-law+Gaussian component is not.  Extending this out to using the ungrouped data in this session, and using group_counts and adding quality flags to the data from within Sherpa, it also fails: 

```
load_data(2,"18076.pi") 
quality = numpy.zeros(len(get_data().channel)) 
for i in range(len(quality)): 
     if i+1<=35: 
         quality[i]=-1 
     elif i+1>=501: 
         quality[i]=-1 
set_quality(2,quality) 
group_counts(2,5) 
set_full_model(2,rmf(arf(xswabs.abs1*(xszwabs.abs2*powlaw1d.pl1)))+bkg_scale*(rmf(arf(xswabs.bkgabs*(xsapec.bkgapec))+(powlaw1d.bkgpl+xsgaussian.bkgg1+xsgaussian.bkgg2)))) 
ignore_bad(2) 
fit(2) 
*** 
WARNING: data set 2 has associated backgrounds, but they have not been 
subtracted, nor have background models been set 
ValueError: shape mismatch between 'ARFModelPHA: 1070' and 'BinaryOpModel: 
1063 
*** 
```

Starting a new Sherpa session and loading the ungrouped spectrum of that source gives no issues. The fit works fine. 

```
import numpy
load_data("18076.pi") 
quality=numpy.zeros(len(get_data().channel)) 
for i in range(len(quality)): 
     if i<=34: 
         quality[i]=1 
     elif i>=477:
         quality[i]=1
rmf = get_rmf() 
arf = get_arf() 
bkg_scale = get_bkg_scale() 
set_quality(quality) 
group_counts(5) 
set_full_model(rmf(arf(xswabs.abs1*(xszwabs.abs2*powlaw1d.pl1)))+bkg_scale*(rmf(arf(xswabs.bkgabs*(xsapec.bkgapec))+(powlaw1d.bkgpl+xsgaussian.bkgg1+xsgaussian.bkgg2)))) 
ignore_bad() 
fit() 
```

Similarly, the grouped spectrum can also be fit this time. 

```
load_pha(2,"18076_bin5.pi") 
set_full_model(2,rmf(arf(xswabs.abs1*(xszwabs.abs2*powlaw1d.pl1)))+bkg_scale*(rmf(arf(xswabs.bkgabs*(xsapec.bkgapec))+(powlaw1d.bkgpl+xsgaussian.bkgg1+xsgaussian.bkgg2)))) 
ignore_bad(2) 
fit(2) 
```

There seems to be something up with how ignore_bad() resizes the spectrum grid -- and it seems inconsistent too. Even ungrouping the Sherpa-grouped data can trigger a similar failure. 

# Notes

The user's actions create a case whereas both quality and group flags are set, but Sherpa fails to   combine the information properly. In particular, `ignore_bad()` sets the quality filter to a state that is incompatible with the grouping that was applied when the binned file was read. 

(Also, `group_counts()` overwrites the quality flags, which will be addressed in bug #233.)

**Comment by joleroi** [comment]
I have a similar issue

```
sherpa-1> load_pha('3c273.pi')
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi
sherpa-2> resp = get_response()
sherpa-3> bkg_scale = get_bkg_scale()
sherpa-4> set_full_model(resp(bbody.source) + bkg_scale * bbody.background)
sherpa-5> notice(2,20)
sherpa-6> fit()
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
ValueError: shape mismatch between 'RSPModelPHA: 1024' and 'BinaryOpModel: 891'
```

The problem is, however, a little bit simpler, since I don't do any grouping. I think the issue is that Sherpa does not understand that the background model component is to be evaluate in counts space, or rather only in the noticed counts space.

**Comment by DougBurke** [comment]
Hmmmm, if I add in a `plot_fit` call before the fit, then it succeeds and shows something (I haven't checked to see if it is actually correct). So why does that work but the subsequent call to fit fail?

(I used the master branch just to show it also happens there, ie hasn't been changed recently)

```
% ipython --pylab
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: Qt4Agg

In [1]: from sherpa.astro import ui
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find xpaget on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: ui.load_pha('3c273.pi')
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi

In [3]: rsp = ui.get_response()

In [4]: bscale = ui.get_bkg_scale()

In [5]: ui.set_full_model(rsp(ui.bbody.src) + bscale * ui.bbody.bground)

In [6]: ui.notice(2, 20)

In [7]: ui.plot_fit()

In [8]: ui.get_data_plot_prefs()['ylog'] = True

In [9]: ui.plot_fit()

In [10]: ui.fit()
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-e8187f94ef1e> in <module>()
----> 1 ui.fit()

<string> in fit(id, *otherids, **kwargs)

/stuff/sherpa/sherpa-master/sherpa/astro/ui/utils.pyc in fit(self, id, *otherids, **kwargs)
   9260         """
   9261         kwargs['bkg_only'] = False
-> 9262         self._fit(id, *otherids, **kwargs)
   9263 
   9264     def fit_bkg(self, id=None, *otherids, **kwargs):

/stuff/sherpa/sherpa-master/sherpa/astro/ui/utils.pyc in _fit(self, id, *otherids, **kwargs)
   9364                     i).mask & numpy.isfinite(self.get_data(i).get_x())
   9365 
-> 9366         res = f.fit(**kwargs)
   9367         res.datasets = ids
   9368         self._fit_results = res

/stuff/sherpa/sherpa-master/sherpa/fit.pyc in run(fit, *args, **kwargs)
     56     def run(fit, *args, **kwargs):
     57         fit.model.startup()
---> 58         result = func(fit, *args, **kwargs)
     59         fit.model.teardown()
     60         return result

/stuff/sherpa/sherpa-master/sherpa/fit.pyc in fit(self, outfile, clobber)
   1104             raise FitErr('statnotforbackgsub', self.stat.name)
   1105 
-> 1106         init_stat = self.calc_stat()
   1107         # output = self.method.fit ...
   1108         output = self._iterfit.fit(self._iterfit._get_callback(outfile, clobber),

/stuff/sherpa/sherpa-master/sherpa/fit.pyc in calc_stat(self)
   1007         """
   1008         dep, staterror, syserror = self.data.to_fit(self.stat.calc_staterror)
-> 1009         model = self.data.eval_model_to_fit(self.model)
   1010         bkg_data = self._iterfit.get_bkg_data(dep)
   1011         valid_args = get_valid_args(self.stat.calc_stat)

/stuff/sherpa/sherpa-master/sherpa/astro/data.pyc in eval_model_to_fit(self, modelfunc)
   1192 
   1193     def eval_model_to_fit(self, modelfunc):
-> 1194         return self.apply_filter(modelfunc(*self.get_indep(filter=True)))
   1195 
   1196     def sum_background_data(self,

/stuff/sherpa/sherpa-master/sherpa/models/model.pyc in __call__(self, *args, **kwargs)
    161         if (len(args) == 0 and len(kwargs) == 0):
    162             return self
--> 163         return self.calc([p.val for p in self.pars], *args, **kwargs)
    164 
    165     def _get_thawed_pars(self):

/stuff/sherpa/sherpa-master/sherpa/models/model.pyc in calc(self, p, *args, **kwargs)
    471             raise ValueError("shape mismatch between '%s: %i' and '%s: %i'" %
    472                              (type(self.lhs).__name__, len(lhs),
--> 473                               type(self.rhs).__name__, len(rhs)))
    474         return val
    475 

ValueError: shape mismatch between 'RSPModelPHA: 1024' and 'BinaryOpModel: 891'

```

If I use `ui.calc_stat()` then it also errors out with a shape-mismatch error at the same place.

**Comment by jbudynk** [comment]
Is the file you're using from the [sherpa-test-data](https://github.com/sherpa/sherpa-test-data) repo, or from the Sherpa website (http://cxc.harvard.edu/sherpa4.8/threads/gettingstarted/)? If so, that file is already grouped:

```
sherpa-1> load_pha('3c273.pi')
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi
sherpa-2> get_data().grouped
          True
```

However, your test highlights the same issue. If I ungroup the data first, then follow your steps, I get the same error:

```
sherpa-1> load_pha('3c273.pi')
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi
sherpa-2> ungroup()
sherpa-3> get_data().grouped
          False
sherpa-4> resp = get_response()
sherpa-5> bkg_scale = get_bkg_scale()
sherpa-6> set_full_model(resp(bbody.source) + bkg_scale * bbody.background)
sherpa-7> notice(2, 20)
sherpa-8> fit()
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
  File "/soft/ciao-4.8/ots/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3032, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-749b6e6de45a>", line 1, in <module>
    fit()
  File "<string>", line 1, in fit
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", line 9259, in fit
    self._fit(id, *otherids, **kwargs)
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", line 9363, in _fit
    res = f.fit(**kwargs)
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/fit.py", line 58, in run
    result = func(fit, *args, **kwargs)
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/fit.py", line 1106, in fit
    init_stat = self.calc_stat()
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/fit.py", line 1009, in calc_stat
    model = self.data.eval_model_to_fit(self.model)
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/astro/data.py", line 1181, in eval_model_to_fit
    return self.apply_filter(modelfunc(*self.get_indep(filter=True)))
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/models/model.py", line 163, in __call__
    return self.calc([p.val for p in self.pars], *args, **kwargs)
  File "/soft/ciao-4.8/lib/python2.7/site-packages/sherpa/models/model.py", line 473, in calc
    type(self.rhs).__name__, len(rhs)))
ValueError: shape mismatch between 'RSPModelPHA: 1024' and 'BinaryOpModel: 888'
```

**Comment by DougBurke** [comment]
I was using the `sherpa-test-data/sherpatest/3c273.pi` file.

**Comment by joleroi** [comment]
Maybe this helps

```
In [1]: import sherpa.astro.ui as sau
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: sau.load_pha('/home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273.pi')
   ...: 
WARNING: systematic errors were not found in file '/home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file '/home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file /home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273.arf
read RMF file /home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file '/home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file '/home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file /home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273_bg.pi

In [3]: resp = sau.get_response()

In [4]: full_model = resp(sau.bbody.src) + 0.1 * sau.bbody.bkg

In [5]: len(full_model(2))
Out[5]: 1024

In [6]: full_model([1,2,3,4,5])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-bd5f65f11187> in <module>()
----> 1 full_model([1,2,3,4,5])

/home/kingj/Software/sherpa/sherpa/models/model.pyc in __call__(self, *args, **kwargs)
    161         if (len(args) == 0 and len(kwargs) == 0):
    162             return self
--> 163         return self.calc([p.val for p in self.pars], *args, **kwargs)
    164 
    165     def _get_thawed_pars(self):

/home/kingj/Software/sherpa/sherpa/models/model.pyc in calc(self, p, *args, **kwargs)
    471             raise ValueError("shape mismatch between '%s: %i' and '%s: %i'" %
    472                              (type(self.lhs).__name__, len(lhs),
--> 473                               type(self.rhs).__name__, len(rhs)))
    474         return val
    475 

ValueError: shape mismatch between 'RSPModelPHA: 1024' and 'BinaryOpModel: 5'
```

**Comment by DougBurke** [comment]
Thanks. I wonder what `sherpa.astro.ui.plot_fit` is doing to avoid this; is it evaluating the full model and filtering afterwards (which sounds unlikely)?

**Comment by DougBurke** [comment]
Aha, if you look in `sherpa/astro/plot.py` for the `ModelHistogram` class you can see that it does indeed evaluate the full model and filter afterwards. This doesn't help solve the problem, but explains something to me (my guess is that the approach ModelHistogram uses isn't what we'd want to do in the general case, since it is likely to be approximate due to the whole channel <-> energy mapping with RMFs that is the cause of all this in the first place).

**Comment by joleroi** [comment]
Indeed, the problem is a little bit deeper. Even if you don't apply any filtering and just evaluate the full model at a certain energy it gives you a wrong answer. 
```
In [2]: full_model
Out[2]: <BinaryOpModel model instance '(apply_rmf(apply_arf((38564.6089269 * bbody.src))) + (0.1 * bbody.bkg))'>

In [3]: len(full_model.lhs(2))
Out[3]: 1024

In [4]: full_model.rhs(2)
Out[4]: 0.062607057099866262

In [5]: full_model(2)[-10:-1]
Out[5]:
array([ 0.06260706,  0.06260706,  0.06260706,  0.06260706,  0.06260706,
        0.06260706,  0.06260706,  0.06260706,  0.06260706])
```
The folded term is evaluated in energy space but returns a counts histogram (due to the RMF folding) whereas the unfolded term is also evaluated in energy space and the value is added to all channels as a constant. What should happen is that the unfolded terms is called with a vector of channel energies or so, I guess. This looks like a conceptual problem, however from Example 3 on this page http://cxc.harvard.edu/sherpa/ahelp/set_full_model.html it looks like it is foreseen that people fit background shapes without knowing the background responses. 
One possibility might be to fold the background model with a 'dummy' i.e. unit matrix RMF.

**Comment by DougBurke** [comment]
@joleroi I think this is now a separate issue from #234 - could you make a new issue so we don't forget about it?

**Comment by anetasie** [comment]
Yes, this should be opened as a different issues. 

In theory if there is an instrument background given per channel then the set_full_model() expression
can include non-RMF convolve part, but in the case presented here the background is assumed to be the standard background pha file, which needs a dummy response to translate the background counts to the appropriate channels.

**Comment by joleroi** [comment]
I don't think I understand why this is a different issue and I also don't understand this statement :grin: 

> but in the case presented here the background is assumed to be the standard background pha file, which needs a dummy response to translate the background counts to the appropriate channels. 

If you have a clearer idea what the problem is, can one of you open the new issue, please?

**Comment by joleroi** [comment]
Just for clarity: In the long run I want to provide a instrument background per channel, but this doesn't work for another reason (see https://github.com/sherpa/sherpa/issues/246)

**Comment by DougBurke** [comment]
Going back to  @jbudynk's comment https://github.com/sherpa/sherpa/issues/234#issuecomment-241445507 then you get the same problem if you remove the background scaling - that is if you use

```
set_full_model(resp(bbody.source) + bbody.background)
```

The probelm is, as @anetasie mentioned at https://github.com/sherpa/sherpa/issues/234#issuecomment-241917573 , that we need to add a "dummy response" around the `bbody.background` term (to convert between PHA channel and energy units). We can do this (with the recent-ish create_arf / create_rmf_xxx routines it's relatively easy to create a dummy response), I just need to document it.

**Comment by DougBurke** [comment]
Well, documenting it isn't as easy as I'd hoped, since I still get a 1024 vs 888 bin issue, even with the following (because of the internal filtering done by the response objects during a fit, which explains some of the differences we get with calc_stat vs fit):

```
import numpy as np
from sherpa.astro.ui import *

load_pha('/home/dburke/sherpa/sherpa-master/sherpa-test-data/sherpatest/3c273.pi')
pha = get_data()

ungroup()
assert not pha.grouped

bkg_scale = get_bkg_scale()

resp = get_response()

# need to create an "ideal" response. I can not
# use Response1D since this uses the PHA data
# (should allow this to be over-ridden).
#

# egrids = get_arf().get_indep()

# fake_arf = create_arf(*egrids)
# fake_rmf = create_rmf(*egrids, e_min=egrids[0], e_max=egrids[1])

chans = np.arange(1, 1025)
fake_arf = create_arf(chans, chans+1)

# from sherpa.astro.instrument import RSPModelPHA
# iresp1 = RSPModelPHA(fake_arf, fake_rmf, pha, bbody.background)

# we need to map between 1024 channels and 1090 energies,
# or we can just ignore this and use a channel-only approach

from sherpa.astro.instrument import ARFModelPHA
iresp2 = ARFModelPHA(fake_arf, pha, bbody.background)

# set_full_model(resp(bbody.source) + bkg_scale * iresp1)
set_full_model(resp(bbody.source) + bkg_scale * iresp2)

print(get_model())

notice(2, 20)

fit()
```
