### ISSUE TITLE
issue with sample_flux on Python 3

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#276]
The function `sample_flux` throws an exception when run under Python 3, in the following case:

``` python
from sherpa.astro import ui

load_pha('sherpa-test-data/sherpatest/3c273.pi')
set_model('polynom1d.p1')
fit()
covar()
scal = get_covar_results().parmaxes
sample_flux(p1, 0.5, 1, num=5, correlated=False, scales=scal)
```

```
Traceback (most recent call last):
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/pdb.py", line 1661, in main
    pdb._runscript(mainpyfile)
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/vagrant/test_kenny.py", line 1, in <module>
    from sherpa.astro.ui import *
  File "<string>", line 1, in sample_flux
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/site-packages/sherpa/astro/ui/utils.py", line 11521, in sample_flux
    bkg_id=bkg_id)
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/site-packages/sherpa/astro/ui/utils.py", line 11383, in sample_energy_flux
    scales)
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/site-packages/sherpa/astro/flux.py", line 91, in sample_flux
    samples = sampler.get_sample(fit, samples, num=num)
  File "/home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/site-packages/sherpa/sim/sample.py", line 260, in get_sample
    val, scale, int(num)) for val, scale in izip(vals, scales)]
TypeError: zip argument #2 must support iteration
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/vagrant/miniconda2/envs/sherpa3/lib/python3.5/site-packages/sherpa/sim/sample.py(260)get_sample()
-> val, scale, int(num)) for val, scale in izip(vals, scales)]
```

**Comment by DougBurke** [comment]
Can we close this now as #283 has been merged?
