### ISSUE TITLE
numpy 1.13 error "boolean index did not match indexed array along dimension 0" (VisibleDeprecationWarning with numpy 1.12)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#361]
The following code creates a `VisibleDeprecationWarning` (I'm using one of the data sets in sherpa/sherpa-test-data/) with numpy 1.12 but it fails with numpy 1.13:

```
from sherpa.astro import ui

ui.load_data('/path/to/sherpa-test-data/sherpatest/q1127_src1_grp30.pi')

ui.set_stat('chi2xspecvar')
ui.set_source(ui.xspowerlaw.pl * ui.xsphabs.gal)

ui.calc_stat_info()

ui.notice(0.5, 8.0)
ui.ignore_bad()

ui.calc_stat_info()

ui.notice(0.5, 8.0)
ui.calc_stat_info()
```

The output (here using a Python 3.5 build of CIAO 4.9 but also seen in the standalone) is (where I've elided the initial output):

```
...
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/data.py:1557: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1024 but corresponding boolean dimension is 996
  chans = chans[mask]
/home/djburke/local/u35/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/data.py:1557: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1024 but corresponding boolean dimension is 996
  chans = chans[mask]
Dataset               = 1
Statistic             = chi2xspecvar
Fit statistic value   = 9.20204e+10
Data points           = 410
Degrees of freedom    = 407
Probability [Q-value] = 0
Reduced statistic     = 2.26094e+08
```

The `VisibleDeprecationWarning` warnings are coming from the last `calc_stat_info` call - i.e. after the `ignore_bad` and `notice` calls.

Using NumPy 1.13 (Python 3.6) it now errors out:

```
Traceback (most recent call last):
  File "../dep.py", line 16, in <module>
    ui.calc_stat_info()
  File "<string>", line 1, in calc_stat_info
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/ui/utils.py", line 7547, in calc_stat_info
    output = self._get_stat_info()
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/astro/ui/utils.py", line 9468, in _get_stat_info
    statinfo = f.calc_stat_info()
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/fit.py", line 1192, in calc_stat_info
    stat, fvec = self._calc_stat()
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/fit.py", line 1123, in _calc_stat
    return self.stat.calc_stat(self.data, self.model)
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/stats/__init__.py", line 501, in calc_stat
    fitdata, modeldata = self._get_fit_model_data(data, model)
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/stats/__init__.py", line 198, in _get_fit_model_data
    modeldata = data.eval_model_to_fit(model)
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/data.py", line 503, in eval_model_to_fit
    total_model.append(data.eval_model_to_fit(func))
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/astro/data.py", line 1267, in eval_model_to_fit
    return self.apply_filter(modelfunc(*self.get_indep(filter=True)))
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/astro/data.py", line 643, in get_indep
    return (self.get_noticed_channels(),)
  File "/home/djburke/sherpa/sherpa-mine-numpy113/sherpa/astro/data.py", line 1760, in get_noticed_channels
    chans = chans[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1024 but corresponding boolean dimension is 996
```

**Comment by DougBurke** [comment]
See #388 - no fix, just a test - and it is likely related to the filtering/grouping work that @jbudynk has been working on
