### ISSUE TITLE
ImportWarning causes datastack test failure with Python 3.6 and AstroPy 2.0

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#372]
This is from https://github.com/sherpa/sherpa/pull/371#issuecomment-313857096

I have a newly-created conda environment with python 3.6, astropy 2.0, matplotlib, and ipython which fails with this message:

```
% python setup.py test -a '--show-warnings sherpa/astro/datastack/tests/test_datastack.py::test_design::test_case_1'
...
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/djburke/sherpa/sherpa-py36, inifile: pytest.ini
plugins: xvfb-1.0.0
collected 3 items 

sherpa/astro/datastack/tests/test_datastack.py .E

==================================== ERRORS ====================================
_________________ ERROR at teardown of test_design.test_case_1 _________________

    def fin():
        warnings = [w for w in recwarn.list
                    if type(w.message) not in known_warnings or not known(w)]
    
        nwarnings = len(warnings)
        if nwarnings > 0 and pytest.config.getoption(SHOW_WARNINGS_OPTION):
            print("*** Warnings created: {}".format(nwarnings))
            for i, w in enumerate(warnings):
                print("{}/{} {}".format(i + 1, nwarnings, w))
    
>       assert 0 == nwarnings
E       assert 0 == 2

sherpa/conftest.py:148: AssertionError
--------------------------- Captured stdout teardown ---------------------------
*** Warnings created: 2
1/2 {message : ImportWarning("can't resolve package from __spec__ or __package__, falling back on __name__ and __path__",), category : 'ImportWarning', filename : '/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/importlib/_bootstrap.py', lineno : 205, line : None}
2/2 {message : ImportWarning("can't resolve package from __spec__ or __package__, falling back on __name__ and __path__",), category : 'ImportWarning', filename : '/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/importlib/_bootstrap.py', lineno : 205, line : None}
====================== 1 passed, 1 error in 1.41 seconds =======================
``` 

Following https://github.com/astropy/astropy/issues/6025 I've tried adding `from __future__ import absolute_import` to `test_datastack.py` and `plot_matplotlib.py` (since `__init__.py` already has it) and it does not make a difference.

The warning appears because of the call to

```
         datastack.load_pha(ls, use_errors=True)
```

in the test. It's the third line of the test; if you only run the first two lines - which just set up the `ls` variable - then the tests pass, but including the `load_pha` call leads to this. I've had a very-quick look at the code, but the information-flow is complex, so it's not immediately-obvious where the astropy import is made (under the assumption that that is what is causing the warning).

I don't have the time to go back and confirm that we don't see this with astropy 1.3. Note that I have not confirmed that it is actually an interaction with AstroPy that causes the problem; it's just the mostobvious candidate.

My suggestion is that we ignore this warning in the short term (since it seems benign), and try and work out what is going on after the 4.9.1 release.

**Comment by DougBurke** [comment]
As a test, I hacked the pytest fixture so it doesn't check on the warnings - by commenting out the `addfinalizer` call in `capture_all_warnings` - and the datastack tests pass. If I explicitly force `test_case_1` to fail (in the hope of seeing the screen output which should include the warnings) then I see nothing about `ImportWarning` in this case. So I'm not entirely sure where it's coming from. 

I also tried setting `PYTHONWARNINGS=error` before running the test but this errors out immediately due to a deprecation warning somewhere in a non-Sherpa module, and using `PYTHONWARNINGS=error::ImportWarning` didn't provide any extra information

**Comment by DougBurke** [comment]
For reference, here's my conda environment:

```
% conda list
# packages in environment at /home/djburke/miniconda2/envs/sherpa-py36:
#
astropy                   2.0                 np113py36_0  
cycler                    0.10.0                   py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
icu                       54.1                          0  
ipython                   6.1.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
jedi                      0.10.2                   py36_2  
jpeg                      9b                            0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
matplotlib                2.0.2               np113py36_0  
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0  
path.py                   10.3.1                   py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
prompt_toolkit            1.0.14                   py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.34                   py36_0  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytest                    3.1.2                    py36_0  
python                    3.6.1                         2  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
qt                        5.6.2                         4  
readline                  6.2                           2  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```

**Comment by DougBurke** [comment]
I wonder if it has anything to do with our non-standard installation of the `stk` (and `grp`, but we don't use that here) module (see #50)?

**Comment by olaurino** [comment]
For some reason I did not see this on my workstation, but I am seeing it while testing the binaries on ubuntu. I am now forced to look into it ;)

**Comment by DougBurke** [comment]
Something strange is going on. I just haven't been able to pin down exactly
what. So glad to know that I am not the only person seeing this...

One solution, which I think is realistic for this release, is to just add
these warnings to the white list. Long term we need to know what is
happening, but it doesn't look like a terrible problem short term.

Doug

**Comment by olaurino** [comment]
A couple of things I found out: first, I can reproduce the issue with the following test:

```` python
from sherpa.astro import io

def test_pha():
  io.read_pha("/home/vagrant/sherpa/sherpa-test-data/sherpatest/3c273.pi")
````

The second one is that the error is still there if I install Sherpa 4.9.0 in a new conda environment with astropy 2.0. So this doesn't look like something we did (at least not recently).

If I downgrade astropy to 1.3.3, with all the other dependencies intact, I don't get the issue any more. So it doesn't look like this depends on the version of numpy.

**Comment by olaurino** [comment]
So, I can actually reproduce the issue with astropy alone:

```` python
    def test_astropy():
        from astropy.io.fits.hdu.table import BinTableHDU
       BinTableHDU()
````

In Python 3.6 with Astropy 2.0

@DougBurke could you confirm?

If this is the case then we should simply add the warning and report the issue to Astropy, assuming somebody hasn't already.

**Comment by olaurino** [comment]
I can pretty reliably reproduce this issue, also on my workstation, and installing astropy only.

Now, I can imagine that since this happens only with Python 3.6, I have been "lucky" enough not to run the offending test locally in a Python 3.6 environment. But why didn't this show up in Travis?

**Comment by DougBurke** [comment]
here's what I get on my ubuntu laptop with Python 3.6 and AstroPy 2.0
(ignoring the deprecation warnings):

```
% python -Wd
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.io.fits.hdu.table import BinTableHDU
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/extern/six.py:7:
DeprecationWarning: the imp module is deprecated in favour of importlib;
see the module's documentation for alternative uses
  import imp
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/extern/bundled/six.py:60:
ResourceWarning: unclosed file <_io.TextIOWrapper
name='/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/extern/bundled/six.py'
mode='r' encoding='utf-8'>
  class X(object):
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:130:
DeprecationWarning: invalid escape sequence \D
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:235:
DeprecationWarning: invalid escape sequence \P
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:130:
DeprecationWarning: invalid escape sequence \D
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/appdirs.py:235:
DeprecationWarning: invalid escape sequence \P
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:144:
DeprecationWarning: invalid escape sequence \d
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:828:
DeprecationWarning: invalid escape sequence \d
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2652:
DeprecationWarning: invalid escape sequence \d
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2830:
DeprecationWarning: invalid escape sequence \g
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:144:
DeprecationWarning: invalid escape sequence \d
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:828:
DeprecationWarning: invalid escape sequence \d
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2652:
DeprecationWarning: invalid escape sequence \d
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/pyparsing.py:2830:
DeprecationWarning: invalid escape sequence \g
>>> BinTableHdu()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'BinTableHdu' is not defined
>>> BinTableHDU()
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/importlib/_bootstrap.py:205:
ImportWarning: can't resolve package from __spec__ or __package__, falling
back on __name__ and __path__
  return f(*args, **kwds)
/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/importlib/_bootstrap.py:205:
ImportWarning: can't resolve package from __spec__ or __package__, falling
back on __name__ and __path__
  return f(*args, **kwds)
<astropy.io.fits.hdu.table.BinTableHDU object at 0x7eff2f1f8ac8>
>>>
```

so I think we are

a) safe to skip this warning
b) puzzle over why we don't see it on Travis
c) report it to AstroPy

Do you want me to send in an Astropy report, given you're pushed for time?

Doug

**Comment by DougBurke** [comment]
ps excellent detective work on tracking this down.

**Comment by DougBurke** [comment]
Here's a little bit more sleuthing:

```
% python -Werror::ImportWarning -c 'import astropy.io.fits.hdu.table; astropy.io.fits.hdu.table.BinTableHDU()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 800, in __init__
    from ....table import Table
  File "/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/table/__init__.py", line 44, in <module>
    from .column import Column, MaskedColumn, StringTruncateWarning, ColumnInfo
  File "/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/table/column.py", line 32, in <module>
    from .np_utils import fix_column_name
  File "/home/djburke/miniconda2/envs/sherpa-py36/lib/python3.6/site-packages/astropy/table/np_utils.py", line 19, in <module>
    from . import _np_utils
  File "astropy/table/_np_utils.pyx", line 8, in init astropy.table._np_utils (astropy/table/_np_utils.c:5760)
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

**Comment by DougBurke** [comment]
So, this looks to be the same warning @bsipocz is seeing in https://github.com/astropy/astropy/issues/6025#issuecomment-311951088 so I don't think we need to raise an AstroPy issue.

**Comment by olaurino** [comment]
Thanks for the update. I'll white list the warning in the release branch and re-build/re-test all the packages. 

By he way, pytest-warnings seems promising, although I don't think it allows for the same granularity and control we managed to achieve with our custom solution... for instance we only ignore certain warnings on python 3, not on python 2, and maybe we wouldn't miss this feature anyway. That being said, I couldn't have tracked it down so quickly without pytest-warnings.

**Comment by DougBurke** [comment]
Let's add "pytest-warnings" to the things we want to improve about out test suite then!
