### ISSUE TITLE
set_xlog/ylog fail with Python 3

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#393]
The `sherpa.astro.ui.set_xlog` and `set_ylog` commands fail with Python 3.5 but not with Python 2.7. The following is using the CIAO 4.9 version of Sherpa but I expect the same behavior with the master branch. I have not audited the code to see if there are other functions which fail in a similar manner - such as `set_xlinear` - but I expect them to.

A) Python 2.7

```
sherpa-1> get_data_plot_prefs()['xlog']
          False
sherpa-2> get_data_plot_prefs()['ylog']
          False
sherpa-3> set_xlog()
sherpa-4> set_ylog()
sherpa-5> get_data_plot_prefs()['xlog']
          True
sherpa-6> get_data_plot_prefs()['ylog']
          True
sherpa-7> sys.version
          '2.7.11 (default, Apr 27 2016, 13:22:12) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]'
sherpa-8> sherpa._version.get_versions()
           {'full': '10736c4d70fcd3e7d686670e1594103a1819098e', 'version': 'ciao4.9'}
```

B) Python 3.5

```
sherpa-1> get_data_plot_prefs()['xlog']
          False
sherpa-2> get_data_plot_prefs()['ylog']
          False
sherpa-3> set_xlog()
TypeError: 'dict_keys' object is not subscriptable
sherpa-4> set_ylog()
TypeError: 'dict_keys' object is not subscriptable
sherpa-5> get_data_plot_prefs()['xlog']
          False
sherpa-6> get_data_plot_prefs()['ylog']
          False
sherpa-7> sys.version
          '3.5.1 (default, Apr  6 2016, 12:14:18) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]'
sherpa-8> sherpa._version.get_versions()
          {'full': '10736c4d70fcd3e7d686670e1594103a1819098e', 'version': 'ciao4.9'}
```

**Comment by DougBurke** [comment]
This looks similar to #303 (hard to tell as the actual error wasn't reported), which added a test to check that `set_xlog` works. So what is going on ?

**Comment by DougBurke** [comment]
Aha, it appears to be a problem with `sherpa.astro.ui`:

```
% python -c 'from sherpa import ui; ui.set_xlog()'
WARNING: failed to import sherpa.plot.pylab_backend; plotting routines will not be available
```

but

```
% python -c 'from sherpa.astro import ui; ui.set_xlog()'
WARNING: failed to import sherpa.plot.pylab_backend; plotting routines will not be available
WARNING: failed to import sherpa.astro.io; FITS I/O routines will not be available
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in set_xlog
  File "/home/djburke/sherpa/sherpa-set-plot-py3/sherpa/ui/utils.py", line 11430, in set_xlog
    self._set_plot_item(plottype, 'xlog', True)
  File "/home/djburke/sherpa/sherpa-set-plot-py3/sherpa/astro/ui/utils.py", line 10185, in _set_plot_item
    keys = self._plot_types.keys()[:]
TypeError: 'dict_keys' object is not subscriptable
```

**Comment by DougBurke** [comment]
See #396
