### ISSUE TITLE
Should we warn if XSPEC version linked with is not similar to XSPEC build with?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#421]
PR#395 lets us bake in to the build the version of the XSPEC model library used for building the module. I wonder if we should make `_sherpa_init_xspec_library` compare this to the library it loads and to display a warning if they are different ?

If we were to do this, I think we would want to exclude the patch level from the comparison - so it would only warn if build with 12.9.0 and then run with 12.9.1 (or vice versa), but not if built with 12.9.1.c but run with 12.9.1.p.

Why do I think this may be useful? Well, the check added in #395 asserts a run-time check, which is important, but it's also important what the module was built with. For instance, if built with 12.9.0 then you don't get the `XSbtapec` model. However, if I try to run it with 12.9.1 then the module import code is going to think it has support for the model when it actually doesn't.

Note that I don't have much (well, any) experience with trying to use a XSPEC version with Sherpoa different from that used to build Sherpa (apart from by accident), so I don't know if this is actually a serious concern (i.e. maybe the import fails because of missing symbols anyway)

**Comment by olaurino** [comment]
Note that in the case you are mentioning the code would error out with a message like "model but apex not built", so that case is handled.

That does not mean I don't see the value in a warning. I actually do. However that would require tracking something that happened at build time. It could probably be done in the C extension by injecting the version through a macro, and adding a function to the extension that returns that value. Not easy to test (I guess you are volunteering), but feasible.

As you said, we should first check what happens if you try to import and use a different xspec than the one that Sherpa was built against.

**Comment by DougBurke** [comment]
I'm having trouble to get an XSPEC 12.9.0 build on my laptop as I appear to have too new a compiler/set up for the code...

**Comment by DougBurke** [comment]
So, I have pr 395 built against 12.9.1p, and see the following behavior. So, I think that there might be some benefit for checking build vs runtime settings and warn the user [e.g. because it is trying to load in some configuration data that may be different but not result in a crash], but we are unlikely to get to the point of providing a helpful message to say that model "XSbtapec" is not available (because the import will have already failed).

# with XSPEC 12.9.1 HEASOFT env variable only

```
% export HEADAS=/lagado.real/local/heasoft-6.22.1/x86_64-unknown-linux-gnu-libc2.12
% python -c 'from sherpa.astro import xspec; print(xspec.get_xsversion());'
12.9.1p
```

# with XSPEC 12.9.0 HEASOFT env variable only

```
% export HEADAS=/lagado.real/local/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12
% python -c 'from sherpa.astro import xspec; print(xspec.get_xsversion());'
12.9.1p
```

Why is this? Because I have not changed my LD_LIBRARY_PATH and so it is using the path from build time - e.g.

```
% ldd ./sherpa/astro/xspec/_xspec.cpython-36m-x86_64-linux-gnu.so | grep XS
	libXSFunctions.so => /lagado.real/local/heasoft-6.22.1/x86_64-unknown-linux-gnu-libc2.12/lib/libXSFunctions.so (0x00007f3146c08000)
	libXSModel.so => /lagado.real/local/heasoft-6.22.1/x86_64-unknown-linux-gnu-libc2.12/lib/libXSModel.so (0x00007f3146851000)
	libXSUtil.so => /lagado.real/local/heasoft-6.22.1/x86_64-unknown-linux-gnu-libc2.12/lib/libXSUtil.so (0x00007f31465cb000)
```

# What about if I set up for XSPEC 12.9.0 ?

```
% . /lagado.real/local/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12/headas-init.sh 
% python -c 'from sherpa.astro import xspec; print(xspec.get_xsversion());'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lagado.real/sherpa/sherpa-pr395/sherpa/astro/xspec/__init__.py", line 53, in <module>
    from .utils import ModelMeta, version_at_least
  File "/lagado.real/sherpa/sherpa-pr395/sherpa/astro/xspec/utils.py", line 21, in <module>
    from . import _xspec
ImportError: /lagado.real/sherpa/sherpa-pr395/sherpa/astro/xspec/_xspec.cpython-36m-x86_64-linux-gnu.so: undefined symbol: C_btapec
```

**Comment by olaurino** [comment]
If you do the opposite, i.e build on the lower version, then run with the higher version and try to call a model that is only available in the higher version, I'd expect everything to work until the model is called and an exception is raised with a message like "function was not built".

**Comment by DougBurke** [comment]
Here's what I got when compiling against HEADAS 6.18 / XSPEC 12.9.0i and then switching to HEADAS 6.22.1 / XSPEC 12.9.1p. It looks sensible to me (note that there's always a possibility that a symbol we used in compiling our XSPEC interface will be removed in a later version, which would lead to a similar import error as seen in my previous check, but that's not true for now at least).

# with HEADAS 6.18 env var only

```
% export HEADAS=/lagado.real/local/heasoft-6.18/x86_64-unknown-linux-gnu-libc2.12
% python -c 'from sherpa.astro import xspec; print(xspec.get_xsversion());'
12.9.0i
```

# with HEADAS 6.22.1 env variable only

```
% export HEADAS=/lagado.real/local/heasoft-6.22.1/x86_64-unknown-linux-gnu-libc2.12
% python -c 'from sherpa.astro import xspec; print(xspec.get_xsversion());'
12.9.0i
```

# setting up LD_LIBRARY_PATH to pick up HEADAS 6.22.1

```
% . /lagado.real/local/heasoft-6.22.1/x86_64-unknown-linux-gnu-libc2.12/headas-init.sh 
% python -c 'from sherpa.astro import xspec; print(xspec.get_xsversion());'
12.9.1p
```

What happens if I try a model which is in XSPEC 12.9.1 but not 12.9.0 (`XSbtapec`):

```
% python
Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sherpa.astro.xspec import XSbtapec
>>> mdl = XSbtapec()
>>> mdl.version_enabled
True
>>> mdl([0.1, 0.2, 0.3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lagado.real/sherpa/sherpa-pr395/sherpa/models/model.py", line 170, in __call__
    return self.calc([p.val for p in self.pars], *args, **kwargs)
  File "/lagado.real/sherpa/sherpa-pr395/sherpa/models/model.py", line 65, in cache_model
    vals = func(cls, pars, xlo, *args, **kwargs)
  File "/lagado.real/sherpa/sherpa-pr395/sherpa/astro/xspec/__init__.py", line 344, in calc
    out = self._calc(*args, **kwargs)
  File "/lagado.real/sherpa/sherpa-pr395/sherpa/astro/xspec/utils.py", line 61, in _not_compiled
    raise AttributeError(ModelMeta.NOT_COMPILED_FUNCTION_MESSAGE)
AttributeError: Calling an xspec function that was not compiled
```

**Comment by olaurino** [comment]
By the way, I was expecting you to tell me that `AttributeError` was not the right error type. Do you think it is?

**Comment by DougBurke** [comment]
Well, I guess technically it should be a `sherpa.utils.Err`-derived error, but I think we should discuss whether this abstraction is worth it (I think it's probably not, even though I was likely the one who essentially asked for it).

If we didn't go with `AttributeError`, then I think it would have to be `RuntimeError`. I think I'm happy with `AttributeError`.
