### ISSUE TITLE
iterative fit primini failing in CIAO 4.9

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#431]
From the CXC help desk:

A helpdesk user reported an issue while fitting a spectrum with iterative fitting using the Primini method, but don't see the issue when using sigma rejection, returning a "TypeError: len() of unsized object".  This fit would work in Sherpa in CIAO 4.8.

Setting things up:

```
load_data("3c273.pi")
subtract()
set_source(xsphabs.abs1 * xsapec.cl1)
```

if I immediately do a fit, it runs, but as soon as I set:

```
sherpa-16> set_iter_method("primini")
sherpa-17> fit()
TypeError: len() of unsized object
```

and if I try backing out the iterative fitting, the problem continues to now persist, even though if I had just the default from the beginning, the fit would run.

```
sherpa-18> set_iter_method("none")
sherpa-19> fit()
TypeError: len() of unsized object
```

It seems like the problem was introduced in Sherpa 4.9.0, where I saw that there's a mention about changes to sherpa.fit.Fit (PR 287, https://github.com/sherpa/sherpa/pull/287), and it's noted:

"I added explicit tests of the sigma-rejection iterated-fit routine in this PR (to check that the changes did not change its behavior) but there are no tests of the primini iterated-fit routine."

Is there any possible workaround to this problem?

**Comment by olaurino** [comment]
here is a minimal script (the dataset is taken from Nick's pool space):

```
from sherpa.astro.ui import *
load_data("3c273.pi")
set_source(powerlaw.p1)
set_iter_method("primini")
fit()
```

With the help of git bisect I found that the commit introducing the bug is 88788da52

Here is the full stack trace:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    fit()
  File "<string>", line 1, in fit
  File "/export/working/sherpa/sherpa/astro/ui/utils.py", line 9262, in fit
    self._fit(id, *otherids, **kwargs)
  File "/export/working/sherpa/sherpa/astro/ui/utils.py", line 9366, in _fit
    res = f.fit(**kwargs)
  File "/export/working/sherpa/sherpa/fit.py", line 59, in run
    result = func(fit, *args, **kwargs)
  File "/export/working/sherpa/sherpa/fit.py", line 1127, in fit
    self.model.thawedparmaxes)
  File "/export/working/sherpa/sherpa/fit.py", line 915, in fit
    statargs, statkwargs)
  File "/export/working/sherpa/sherpa/fit.py", line 673, in primini
    current_stat = statfunc(pars)[0]
  File "/export/working/sherpa/sherpa/fit.py", line 583, in cb
    stat = self.stat.calc_stat(self.data, self.model)
  File "/export/working/sherpa/sherpa/stats/__init__.py", line 492, in calc_stat
    data, model = self._validate_inputs(data, model)
  File "/export/working/sherpa/sherpa/stats/__init__.py", line 195, in _validate_inputs
    self._check_has_bins(data)
  File "/export/working/sherpa/sherpa/stats/__init__.py", line 131, in _check_has_bins
    dep, _, _ = dset.to_fit(staterrfunc=None)
  File "/export/working/sherpa/sherpa/astro/data.py", line 1747, in to_fit
    self.get_staterror(True, staterrfunc),
  File "/export/working/sherpa/sherpa/astro/data.py", line 1272, in get_staterror
    staterr = self.apply_filter(staterr, self._sum_sq)
  File "/export/working/sherpa/sherpa/astro/data.py", line 752, in apply_filter
    elif len(data) != len(self.counts):
TypeError: len() of unsized object
```

At some point the staterror field for a DataPHA object is set to 1. I suspect the problem is on this line:

https://github.com/sherpa/sherpa/blob/88788da52/sherpa/fit.py#L667

When get_staterror returns a None, because:

```
In [1]: import numpy

In [2]: a = numpy.ones_like(None)

In [3]: len(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-af8c77e09569> in <module>()
----> 1 len(a)

TypeError: len() of unsized object
```

I guess get_staterror() was never returning None before this commit and now it is. Or, if it was returning None, it was handled differently.

**Comment by anetasie** [comment]
In one of the discussions we decided to deprecate the Primini statistics. I'm closing this issue.
