### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by dtnguyen2** [sherpa/sherpa#442]
Model evaluation
    - Model caching, not to recompute models with frozen parameters
    - Paralellization with intelligent parsing of the model expression
 Slowness in fitting X-ray spectra
    - issues in simultaneous fitting of multiple data (more general) - do  not reevaluate the models with the
      same parameters multiple times
 Parallelization for MonCar and Nelder-Mead methods:
   - lower priority until the two parts as described above are done

**Comment by JohannesBuchner** [comment]
> Model evaluation
> - Model caching, not to recompute models with frozen parameters
> - Paralellization with intelligent parsing of the model expression
> Slowness in fitting X-ray spectra
> - issues in simultaneous fitting of multiple data (more general) - do not reevaluate the models with the
> same parameters multiple times

These would be great. Another low-hanging fruit improvement would be to *not* recomputing apec (and other xspec models) shape if only the normalization parameter was changed.

We are fitting a sum of 10 apecs with the temperatures fixed in logarithmic steps, where the normalisations are linked to a formula whose parameters are varied. There is no real reason why this should be slow.

So I'd propose model caching, not to recompute models with _unchanged_ parameters. This can be achieved with memoization.

I placed a practical benchmark here: https://github.com/JohannesBuchner/xray-fit-benchmark

**Comment by hamogu** [comment]
In general, models are cached in Sherpa using the https://github.com/sherpa/sherpa/blob/80b22a87b77d73f21444bd3a159f16df14af6a57/sherpa/models/model.py#L373 decorator. 

I'm not sure what @dtnguyen2 had in mind when he wrote that, but the first bullet should be solved by now. 

I agree with 
> Another low-hanging fruit improvement would be to not recomputing apec (and other xspec models) shape if only the normalization parameter was changed.

Unfortunately, that's a little harder to implement in a general sense: For all XSPEC models, we pass all model parameters to the XSPEC function. There is no special markup which of those is the norm and which of those require a re-compute. We could make an informed guess that any parameter with the substring "norm" in it may not require a recomputation, but that's seem brittle (it would work for APEC, though). 

However, you should be able to achieve the same effect by changing your model definitions; instead of `set_source(apec.a1 + apec.a2)` you could do 
```
sect_source(scale1d.norm1 * apec1.a1 + scale1d.norm2 * apec.a2)
a1.norm = 1
a2.norm =1
# freeze all the apec parameters ...
```
Because there are no changes to any of the parameters for apec1 and apec2 in the fitting loop now, it should not be eveluated again.

**Comment by JohannesBuchner** [comment]
Thanks @hamogu!

>  Unfortunately, that's a little harder to implement in a general sense: For all XSPEC models, we pass all model parameters to the XSPEC function. There is no special markup which of those is the norm and which of those require a re-compute. We could make an informed guess that any parameter with the substring "norm" in it may not require a recomputation, but that's seem brittle (it would work for APEC, though).

Maybe sherpa could maintain a list of additive models for which "norm" exists and this is safe to do, and automatically wrap those, i.e., add a scale1d.norm and keep xspec.norm=1.

With your workaround, the speed increased from 15 model evaluations per second to 20 model evaluations per second.

I could not apply `modelCacher1d` to the xspec table model:
```
Traceback (most recent call last):
  File "generateconst.py", line 28, in <module>
    mymodel = xstbabs.galabso * (scale1d.torusnorm * modelCacher1d(torus) + scale1d.omninorm * modelCacher1d(omni))
  File "/home/user/bin/ciao-4.13/lib/python3.7/site-packages/sherpa-4.13.0-py3.7-linux-x86_64.egg/sherpa/models/model.py", line 86, in modelCacher1d
    cache_model.__name__ = func.__name__
  File "/home/user/bin/ciao-4.13/lib/python3.7/site-packages/sherpa-4.13.0-py3.7-linux-x86_64.egg/sherpa/models/model.py", line 203, in __getattr__
    NoNewAttributesAfterInit.__getattribute__(self, name)
AttributeError: 'XSTableModel' object has no attribute '__name__'
```

**Comment by DougBurke** [comment]
Also see #1782

**Comment by hamogu** [comment]
@JohannesBuchner The caching for XSPEC models should already be applied without you doing things. @DougBurke is the master of knowing how it's done, but the goal is that, as a user, you don't have to do anything because we apply sensible caching as default.

**Comment by hamogu** [comment]
> FYI I don't have much time to spend time on so it'll take some time for me to respond.
It took me some time to count how many times the word "time" can be used in a sentence with < 20 words..

**Comment by hamogu** [comment]
But seriously, there is a trade-off between developer time and run-time. The suggestion in https://github.com/sherpa/sherpa/issues/442#issuecomment-1845612188 should work in principle, but it's not simple in any sense. 
It requires treating certain model parameters special, starting with XSPEC model norms. But why stop there? How about norms in Sherpa models? Or in user-defined models?
I'm not saying it won't work and it's not worthwhile to do in Sherpa itself or at least as a documented "work-around" for users that do need that speed-up in some case. What I am saying is that I don't know if that's the most efficient use of limited developer time or if there are other bottlenecks that we should address first that are either easier to do or more general and thus bring benefit to more users. 

For that, it would be good to actually write down a few end-to-end workflows that we can benchmark and profile to identify where we should focus our efforts. Is it caching as discussed here? Parallelization? Avoiding temporary copies of big arrays? Move more Python Code to C? Avoid overhead of calling C by moving more code to Python/Numpy? Just-in-time compilation of Python code with Numba / JAX / ...? Find better optimizers / use analytical gradiends/ autograd / to reduce the number of model evaluations needed to get a good fit?

Any of those can help in specific cases, but without profiling a set of representative use cases, I don't know which of those are high or low priority or have a high or low likelihood of success.
