### ISSUE TITLE
Sherpa module setup is complicated, and makes use by sphinx hard

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#456]
As part of my work trying to get sphinx documentation working - issue #197 PR #302 - I am investigating if we can just mock our way out of having to actually build Sherpa before creating the docs (this would need issue #429 addressed for all the compiled modules before fully workable). The somewhat-complicated approach taken by Sherpa when importing modules looks like it's working against us - for instance in the following I try to mock the compiled modules so that I can `import sherpa.models.parameter`, but it gets stuck on `sherpa.utils.testing`.

The following is with python 2.7 and sherpa from pr #302 but I expect the same behavior with the master branch.

```
% python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sherpa.models.parameter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sherpa/models/__init__.py", line 20, in <module>
    from sherpa.models.parameter import *
  File "sherpa/models/parameter.py", line 25, in <module>
    from sherpa.utils import SherpaFloat, NoNewAttributesAfterInit
  File "sherpa/utils/__init__.py", line 37, in <module>
    from . import testing
  File "sherpa/utils/testing.py", line 25, in <module>
    from sherpa.utils._utils import sao_fcmp
ImportError: No module named _utils
>>> from mock import Mock
>>> def mocky(n):
...     sys.modules[n] = Mock()
... 
>>> import sys
>>> mocky('sherpa.utils._utils')
>>> import sherpa.models.parameter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sherpa/models/__init__.py", line 20, in <module>
    from sherpa.models.parameter import *
  File "sherpa/models/parameter.py", line 25, in <module>
    from sherpa.utils import SherpaFloat, NoNewAttributesAfterInit
  File "sherpa/utils/__init__.py", line 42, in <module>
    from sherpa.utils._psf import extract_kernel, normalize, set_origin, \
ImportError: No module named _psf
>>> mocky('sherpa.utils._psf')
>>> import sherpa.models.parameter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sherpa/models/__init__.py", line 20, in <module>
    from sherpa.models.parameter import *
  File "sherpa/models/parameter.py", line 25, in <module>
    from sherpa.utils import SherpaFloat, NoNewAttributesAfterInit
  File "sherpa/utils/__init__.py", line 37, in <module>
    from . import testing
ImportError: cannot import name testing
>>> mocky('sherpa.utils.testing')
>>> import sherpa.models.parameter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sherpa/models/__init__.py", line 20, in <module>
    from sherpa.models.parameter import *
  File "sherpa/models/parameter.py", line 25, in <module>
    from sherpa.utils import SherpaFloat, NoNewAttributesAfterInit
  File "sherpa/utils/__init__.py", line 37, in <module>
    from . import testing
ImportError: cannot import name testing
```

**Comment by olaurino** [comment]
I agree that historically Sherpa's module importing has been more complex than it should have been. However I am not sure whether in this case the culprit is the complex (but legitimate, since for better or worse it works) importing or the fact that in order to build the documentation you need runnable code rather than just static code, or the complexity of configuring the building environment, which by itself is not complex at all.

Note that I can get past the issue you are encountering by mixing mocking and patching in a specific order, but then the import fail with `ImportError: cannot import name _modelfcts`, at least in Python 2, and I can't understand why. The following script seems to work in Python 3, but not in Python 2:

``` python
from __future__ import absolute_import
import mock
import sys

sys.modules['sherpa.utils._psf'] = mock.MagicMock()
sys.modules['sherpa.utils._utils'] = mock.MagicMock()
sys.modules['sherpa.models._modelfcts'] = mock.MagicMock()

with mock.patch('sherpa.utils.testing'):
        import sherpa.models.parameter
```

**Comment by DougBurke** [comment]
A couple of quick notes:

a) https://github.com/sphinx-doc/sphinx/issues/2557 is an interesting read

b) The way I've been trying this is without any building of the code (i.e. no `python setup.py develop` or `python setup.py install`); this could lead to different behavior/results to if you have an install/developer build available.

c) although I explicitly list `sherpa.utils.testing`, this is meant to be a general point (i.e. not just this module)

d) for `sherpa.utils`, I would like to drop the automatic export of `sherpa.utils.testing`, and make code that wants these classes to import them from `sherpa.utils.testing` directly (but that's a different issue)

**Comment by olaurino** [comment]
Is a) what you are trying to do to avoid building Sherpa for the docs? And it's not working just because of the sometimes involved importing?

d) is totally fine with me. It was like that for backward compatibility but I guess it's just fine to fix that.
