### ISSUE TITLE
ELF file OS ABI invalid

### ISSUE THREAD

**Issue by pepgalax** [sherpa/sherpa#480]
I have both anaconda2 and anaconda3 with sherpa installed and I am getting the error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pep/anaconda3/lib/python3.6/site-packages/sherpa/astro/ui/__init__.py", line 20, in <module>
    import sherpa.all
  File "/home/pep/anaconda3/lib/python3.6/site-packages/sherpa/all.py", line 37, in <module>
    from sherpa.fit import *
  File "/home/pep/anaconda3/lib/python3.6/site-packages/sherpa/fit.py", line 36, in <module>
    from sherpa.models import SimulFitModel
  File "/home/pep/anaconda3/lib/python3.6/site-packages/sherpa/models/__init__.py", line 22, in <module>
    from sherpa.models.basic import *
  File "/home/pep/anaconda3/lib/python3.6/site-packages/sherpa/models/basic.py", line 28, in <module>
    from . import _modelfcts
ImportError: /home/pep/anaconda3/lib/python3.6/site-packages/sherpa/models/_modelfcts.cpython-36m-x86_64-linux-gnu.so: ELF file OS ABI invalid

when I do:
import sherpa.astro.ui as ui

Any idea on how to solve this?

**Comment by pepgalax** [comment]
With anaconda2, the error is longer but ends to the same issue:

Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sherpa.ui
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/ui/__init__.py", line 20, in <module>
    import sherpa.all
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/all.py", line 37, in <module>
    from sherpa.fit import *
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/fit.py", line 36, in <module>
    from sherpa.models import SimulFitModel
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/models/__init__.py", line 22, in <module>
    from sherpa.models.basic import *
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/models/basic.py", line 28, in <module>
    from . import _modelfcts
ImportError: /home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/models/_modelfcts.so: ELF file OS ABI invalid

**Comment by pepgalax** [comment]
With anaconda2 the error is longer but ends on the same problem:


Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

import sherpa.ui
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/pep/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/ui/__init__.py", line 20, in <module>
    import sherpa.all
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/all.py", line 37, in <module>
    from sherpa.fit import *
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/fit.py", line 36, in <module>
    from sherpa.models import SimulFitModel
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/models/__init__.py", line 22, in <module>
    from sherpa.models.basic import *
  File "/home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/models/basic.py", line 28, in <module>
    from . import _modelfcts
ImportError: /home/pep/anaconda2/lib/python2.7/site-packages/sherpa-4.10.0-py2.7-linux-x86_64.egg/sherpa/models/_modelfcts.so: ELF file OS ABI invalid

**Comment by olaurino** [comment]
Hi @pepgalax! It looks like a binary incompatibility. What Operating System are you running?

**Comment by pepgalax** [comment]
Thanks for the prompt answer!
It's installed in a cluster.

$ uname -a
Linux  2.6.18-308.el5 #1 SMP Fri Jan 27 17:17:51 EST 2012 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 5.8 (Tikanga)
Release:	5.8
Codename: Tikanga

Thanks!

**Comment by olaurino** [comment]
Sherpa 4.10.0 is not supported on RHEL 5, as it was built on a CentOS 6 system, as per Anaconda minimum system requirements.

You have a few options, depending on your specific needs and setup:
  1. you can install an older version of Sherpa (4.9.0 would work on RHEL 5) through conda.
  2. you could install a special build of 4.9.1 for CentOS 5: `conda install -c cxc/channel/dev sherpa=4.9.1`. See https://github.com/sherpa/sherpa/issues/414 for potential issues with this approach.
  3. you could build Sherpa from sources. Depending on your setup this might or might not be trivial.
  4. you could build a Sherpa conda package using Docker: https://github.com/sherpa/legacy-builds/tree/centos5

Please let me know if you need assistance with any of the above.

**Comment by olaurino** [comment]
I should add that there might be other issues related to RHEL Server vs the CentOS/RHEL releases of the same version, but I am not sure if that is the case.

**Comment by olaurino** [comment]
@pepgalax any news on this?

**Comment by pepgalax** [comment]
Hi @olaurino,

Sorry for the silence. I have tried 1 and 3 without success. Anyway, I am do in it in a cluster where I do not have sudo permissions and there are some additional errors. The IT is on holidays this month and they will try everything at their return in a couple of weeks. I will let you know.

Thanks!

**Comment by olaurino** [comment]
No problem, I'll leave this ticket open for now.
