### ISSUE TITLE
convolution/psf models and session support

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#613]
I am trying to understand the "operational" differences to `load_psf` and `load_conv`, so we can document them better (i.e. when should users use one rather than the other), as this has just come up in a discussion with a user. It's not really related to this ticket, but provides background.

This lead me to look at `sherpa/instrument.py`, and I note that the "Kernel" style models take a `session=None` argument for `__call__`. From looking at the code you can see that this is to support the lookup of a model component when given as a string; the passed in session object provides the name lookup. Both `ConvolutionKernel` and `PSFModel` default to using the "hidden" session object provided by `sherpa.astro.ui` if `session` is set to `None`. This surprised me, since this is not an `astro`-specific module (you see the same thing in `sherpa/astro/instrument.py`, but that makes more sense). My concern is that if you are using `sherpa.ui` then defaulting to `sherpa.astro.ui` could cause problems in certain cases.

I then started to dig around and see how this session argument was sent in (since it's an extension to how models are normally used, but then again these are special-cases where you are actually calling the object to wrap up another model rather than to evaluate it). I couldn't find anywhere which explicitly uses the `session=` parameter name in a call. So I'm wondering if we actually have any code that uses this capability?

For instance (if I'm following things correctly here, which may be wrong, as it is hard to keep track of the types), the `sherpa.utils.Session._add_psf` routine should really say `model = psf(model, session=self)` 

If I get time I'll try to cook up some simple tests to see if I can actually trigger any problems because of all this, or whether it's irrelevant.

---

# Summary

## Question 3: Does it matter/cause any potential problems?

**Comment by olaurino** [comment]
Sometimes this kind of "dead code" is used by Level 3 scripts. Sometimes it is not.

**Comment by DougBurke** [comment]
So, I think there is a problem here:

```
> cat ../test_conv.py
# Does the session=None support cause problems?
#

from sherpa import ui

ui.create_model_component('box1d', 'box')
ui.load_conv('conv', 'box')

mdl1 = conv(box)
mdl2 = conv('box')
```

The creation of `mdl2` fails because it defaults to looking up `'box'` in the `sherpa.astro.ui` session object, but this hasn't been created here:

```
% python ../test_conv.py 
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
Traceback (most recent call last):
  File "../test_conv.py", line 10, in <module>
    mdl2 = conv('box')
  File "/home/dburke/sherpa/sherpa-master/sherpa/instrument.py", line 222, in __call__
    model = sherpa.astro.ui._session._eval_model_expression(model)
AttributeError: module 'sherpa.astro' has no attribute 'ui'
```

If I change the `conv` call to the following it works:

```
mdl2 = conv('box', session=ui._session)
```

**Comment by anetasie** [comment]
Is `load_conv` specific to 1D convolution kernels only?
