### ISSUE TITLE
build issues with XSPEC 12.10.1 patch m

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#676]
From https://heasarc.gsfc.nasa.gov/xanadu/xspec/issues/issues.html

```
12.10.1m

This patch updates rdblur, kdblur, kdblur2, kerrconv for considerable speed improvements 
over previous patches. It also removes the models relline, relline_lp, relline_lp_ext, relconv, 
relconv_lp, relconv_lp_ext since these are older versions to those available through 
the relxill local model package, and have been causing problems for people loading relxill. 
Report added on Aug 14, 2019.This patch modifies heasoft-6.26/Xspec/src/manager/ model.dat, 
src/XSFunctions/ Makefile, funcWrappers.cxx, .h, functionMap.cxx, .h, kerrd.cxx, spin.cxx, 
dospin.f, spinconv.cxx, rdblur.cxx, kdblur.cxx, kdblur2.cxx, src/XSUtil/ Makefile, 
src/XSUtil/Numerics/ Convolution.h.
```

The removal of models is going to cause problems for the build. We could make them conditional, but I propose that we just drop support for the models removed in this patch - they are "convolution" models so are not exposed directly to the user (i.e. there are no model classes that refer to them) and are provided for access for the "interested" users (aka me, who wants to use the new regrid support to finally enable useful support of these models), so I do not expect their removal would affect anyone. They also need dropping post 12.10.1m anyway...

**EDITED TO ADD**

looks like I may have mis-spoke when I said there were no classes providing access to this functionality

**Comment by DougBurke** [comment]
So, with a build against XSPEC 12.10.1f (heasarc 6.26.1) we get

```
% python -c 'import sherpa.astro.xspec; print(sherpa.astro.xspec.get_xsversion())'
12.10.1f
```

but if I install the 12.10.1m patch to HEASARC (and do nothing to Sherpa) we now can not use XSPEC because of these missing symbols (as expected):

```
% python -c 'import sherpa.astro.xspec; print(sherpa.astro.xspec.get_xsversion())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/xspec/__init__.py", line 67, in <module>
    from .utils import ModelMeta, version_at_least, equal_or_greater_than
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/xspec/utils.py", line 21, in <module>
    from . import _xspec
ImportError: /home/dburke/sherpa/sherpa-xspec/sherpa/astro/xspec/_xspec.cpython-37m-x86_64-linux-gnu.so: undefined symbol: tdrellinelp_
```

**Comment by DougBurke** [comment]
With #677 I now get

```
% python -c 'import sherpa.astro.xspec; print(sherpa.astro.xspec.get_xsversion())'
12.10.1m
```
