### ISSUE TITLE
`group_counts` and `ignore` lead to inconsistent bin numbers

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#718]
The following code fails on Sherpa 4.12.0 (conda installed from DS test server):
```
load_pha(1, 'marx_pha.fits')
load_rmf(1, 'marx_rmf.fits')
load_arf(1, 'marx_arf.fits')

group_counts(1, 25)
ignore(None, 0.3)
ignore(7, None)


# set source properties
set_source(xsphabs.a * xspowerlaw.p)
a.nH = 1.0
p.PhoIndex = 1.8
p.norm = 0.001

fit(1)
conf(1)
```
with an error:
```
TypeError: input array sizes do not match, source: 3497 vs effarea: 3498
```
which is issued here: https://github.com/sherpa/sherpa/blob/master/sherpa/astro/utils/src/_utils.cc

While this script *does* work with some other datasets, I still believe this to be a sherpa problem because I can make the script work if:

- I run the `ignore` commands **before** `group_counts`
- I remove either the `ignore` commands or
- I remove the `group_counts` command.

I'm puzzled by what's going on here, because (i) why is the Source array size 3497 when the source has only 1024 bins (I suspect that the array is reformed in C code somewhere, but I did not follow through to check this)? Why do only certain datasets trigger this, but not all of them (The datasets where I saw this all had relatively low count numbers, maybe it's something to do with bins that are empty)?

**Comment by hamogu** [comment]
Data to reproduce is in `/pool14/guenther/sherpa_718` on the HEAD LAN.

**Comment by DougBurke** [comment]
This is odd because if you `plot_fit` instead of `fit` - or call `calc_stat` - then you get a result and not an error. That is, you can evaluate the model for the given data grid. Just not within `fit` (or `conf`).

**Comment by DougBurke** [comment]
in this case it appears to be the `ignore(None, 0.3)` call that causes the problem. That is, a filter that ignores bins at the start. I don't think the 0.3 value is "special" here, since `ignore(None, 2.023)` also causes `fit` to fail. Could there be an off-by-one issue somewhere (although why only for certain datasets and not others)?

Also, as @hamogu mentioned why are there ~3500 elements in the ARF? I assume it's something to do with the RMF/ARF convolution and the sparse-matrix representation of the RMF, but this is a guess.

**Comment by DougBurke** [comment]
So you see this if you do it manually as well (which is not surprising). Given that the initial `f.calc_stat()` call below succeeds, but it doesn't once this method is called from within `fit`, I am not sure what is going on.

Script

```
from sherpa.astro import io
from sherpa.astro.instrument import RSPModelPHA

from sherpa.fit import Fit
from sherpa.models.basic import Const1D

pha = io.read_pha('marx_pha.fits')
arf = io.read_arf('marx_arf.fits')
rmf = io.read_rmf('marx_rmf.fits')

pha.set_arf(arf)
pha.set_rmf(rmf)
pha.units = 'energy'

mdl = Const1D('mdl')
mdl.c0 = 0.01
mdl.integrate = False

fmdl = RSPModelPHA(arf, rmf, pha, mdl)

pha.group_counts(25)
pha.ignore(None, 0.3)

f = Fit(pha, fmdl)
s0 = f.calc_stat()
print("Stat = {}".format(s0))

fres = f.fit()
print(fres.format())
```

and it fails in the same way as above:

```
python manual.py
Stat = 2907.1669684378567
Traceback (most recent call last):
  File "manual.py", line 29, in <module>
    fres = f.fit()
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/fit.py", line 56, in run
    result = func(fit, *args, **kwargs)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/fit.py", line 1231, in fit
    init_stat = self.calc_stat()
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/fit.py", line 1116, in calc_stat
    return self._calc_stat()[0]
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/fit.py", line 1097, in _calc_stat
    return self.stat.calc_stat(self.data, self.model)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/stats/__init__.py", line 546, in calc_stat
    fitdata, modeldata = self._get_fit_model_data(data, model)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/stats/__init__.py", line 206, in _get_fit_model_data
    modeldata = data.eval_model_to_fit(model)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/data.py", line 887, in eval_model_to_fit
    total_model.append(data.eval_model_to_fit(func))
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 1693, in eval_model_to_fit
    return self.apply_filter(modelfunc(*self.get_indep(filter=True)))
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/models/model.py", line 264, in __call__
    return self.calc([p.val for p in self.pars], *args, **kwargs)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/instrument.py", line 573, in calc
    src = self.arf.apply_arf(src, *self.arfargs)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 350, in apply_arf
    model = my_arf_fold(src, self._rsp)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 78, in __call__
    val = self.func(src, rsp)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 88, in my_arf_fold
    return arf_fold(a, b)
TypeError: input array sizes do not match, source: 3497 vs effarea: 3498
```

**Comment by DougBurke** [comment]
It is something to do with the `startup` method (which the `@evaluates_model` decorator causes to be called in `fit`), as the following fails - but does not if the startup line is not included;

```
from sherpa.astro import io
from sherpa.astro.instrument import RSPModelPHA

from sherpa.fit import Fit
from sherpa.models.basic import Const1D

pha = io.read_pha('marx_pha.fits')
arf = io.read_arf('marx_arf.fits')
rmf = io.read_rmf('marx_rmf.fits')

pha.set_arf(arf)
pha.set_rmf(rmf)
pha.units = 'energy'

mdl = Const1D('mdl')
mdl.c0 = 0.01
mdl.integrate = False

fmdl = RSPModelPHA(arf, rmf, pha, mdl)

pha.group_counts(25)
pha.ignore(None, 0.3)

fmdl.startup(cache=False)
pha.eval_model_to_fit(fmdl)
```

which results in

```
Traceback (most recent call last):
  File "manual.py", line 26, in <module>
    pha.eval_model_to_fit(fmdl)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 1693, in eval_model_to_fit
    return self.apply_filter(modelfunc(*self.get_indep(filter=True)))
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/models/model.py", line 264, in __call__
    return self.calc([p.val for p in self.pars], *args, **kwargs)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/instrument.py", line 573, in calc
    src = self.arf.apply_arf(src, *self.arfargs)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 350, in apply_arf
    model = my_arf_fold(src, self._rsp)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 78, in __call__
    val = self.func(src, rsp)
  File "/soft/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/data.py", line 88, in my_arf_fold
    return arf_fold(a, b)
TypeError: input array sizes do not match, source: 3497 vs effarea: 3498
```

**Comment by DougBurke** [comment]
To answer the > 1024 sizes being talked about, note that the ARF has 3900 bins and the RMF has something similar

```
% dmlist marx_arf.fits counts
3900
% dmlist marx_rmf.fits counts
3566    
```

**Comment by DougBurke** [comment]
So, we can see that the filtering to the ARF and RMF that the `startup` method in `RSPModelPHA` causes to happen creates this mis-match. I'm currently guessing it's the logic in `sherpa.astro.data._notice_resp`.

```
% python manual.py
* BEFORE ARF: 0.30000001192092896 - 12.0  nbins=3900
Last bin: 11.996999740600586 - 12.0

* BEFORE RMF: 0.30000001192092896 - 10.998000144958496  nbins=3566
Last bin: 10.994999885559082 - 10.998000144958496

FILTERED ARF: 0.5070000290870667 - 11.00100040435791  nbins=3498
Last bin: 10.998000144958496 - 11.00100040435791

FILTERED RMF: 0.5070000290870667 - 10.998000144958496  nbins=3497
Last bin: 10.994999885559082 - 10.998000144958496

```

which is created by

```
% cat manual.py
from sherpa.astro import io
from sherpa.astro.instrument import RSPModelPHA

from sherpa.fit import Fit
from sherpa.models.basic import Const1D

pha = io.read_pha('marx_pha.fits')
arf = io.read_arf('marx_arf.fits')
rmf = io.read_rmf('marx_rmf.fits')

pha.set_arf(arf)
pha.set_rmf(rmf)
pha.units = 'energy'

mdl = Const1D('mdl')
mdl.c0 = 0.01
mdl.integrate = False

fmdl = RSPModelPHA(arf, rmf, pha, mdl)

pha.group_counts(25)
pha.ignore(None, 0.3)

def report(lbl, obj):
    x1, x2 = obj.get_indep()
    print('{}: {} - {}  nbins={}'.format(lbl, x1[0], x2[-1], x1.size))
    print('Last bin: {} - {}'.format(x1[-1], x2[-1]))
    print('')


report('* BEFORE ARF', fmdl.arf)
report('* BEFORE RMF', fmdl.rmf)

fmdl.startup(cache=False)

report('FILTERED ARF', fmdl.arf)
report('FILTERED RMF', fmdl.rmf)
```

**Comment by DougBurke** [comment]
My current assumption is that there's a "numerical" issue (possibly due to the ranges being treated as elo <= e <= ehi with a tolerance in `sherpa.utils.filter_bins`) that causes an extra bin from the ARF to be included compared to the RMF).

**Comment by DougBurke** [comment]
So, here's a hack that at least makes the `fit`/`conf` call pass (and I can also `plot_fit`/`reg_proj`). The assumption here is that it does the right thing when we don't try to cut down the response information (an optimization done to try and reduce the fit time by avoiding computing bins we don't need), so just skip the response-filtering step which appears to be the problem. See the "Monkey patch" section below (which could be simpler but I wanted to make it obvious for testing what I had changed from the original code).

```
from sherpa.astro import ui

# Monkey patch: start
#
from sherpa.astro.instrument import RSPModelPHA, RSPModel
from sherpa.astro.data import DataARF, DataRMF

def startup_patch(self, cache):
    arf = self._arf
    rmf = self._rmf

    # Create a view of original RMF
    self.rmf = DataRMF(rmf.name, rmf.detchans, rmf.energ_lo, rmf.energ_hi,
                       rmf.n_grp, rmf.f_chan, rmf.n_chan, rmf.matrix,
                       rmf.offset, rmf.e_min, rmf.e_max, rmf.header)

    # Create a view of original ARF
    self.arf = DataARF(arf.name, arf.energ_lo, arf.energ_hi, arf.specresp,
                       arf.bin_lo, arf.bin_hi, arf.exposure, arf.header)

    # Filter the view for current fitting session
    #
    # DJB thinks this is the problem
    # _notice_resp(self.pha.get_noticed_channels(), self.arf, self.rmf)

    self.filter()

    # Assume energy as default spectral coordinates
    self.xlo, self.xhi = self.elo, self.ehi
    if self.pha.units == 'wavelength':
        self.xlo, self.xhi = self.lo, self.hi

    RSPModel.startup(self, cache)

RSPModelPHA.startup = startup_patch

# Monkey patch: end

ui.load_pha('marx_pha.fits')
ui.load_rmf('marx_rmf.fits')
ui.load_arf('marx_arf.fits')

ui.group_counts(1, 25)
ui.ignore(None, 0.3)
ui.ignore(7, None)

ui.set_source(1, ui.xsphabs.a * ui.xspowerlaw.p)

a.nh = 1.0
p.phoindex = 1.8
p.norm = 0.001

ui.fit(1)
ui.conf(1)
```

**Comment by DougBurke** [comment]
I wanted to see how XSPEC handle this, but it refuses to even play thanks to the energy-grid mis-match:

```
% xspec

		XSPEC version: 12.10.1m
	Build Date/Time: Fri Sep  6 10:10:09 2019

XSPEC12>cpd /xw
XSPEC12>data marx_pha.fits 

1 spectrum  in use
 
Spectral Data File: marx_pha.fits  Spectrum 1
Net count rate (cts/s) for Spectrum:1  1.591e-01 +/- 2.317e-03
 Assigned to Data Group 1 and Plot Group 1
  Noticed Channels:  1-1024
  Telescope: CHANDRA Instrument: ACIS  Channel Type: PI
  Exposure Time: 2.962e+04 sec
 Using fit statistic: chi
 Using test statistic: chi
 No response loaded.

***Warning!  One or more spectra are missing responses,
               and are not suitable for fit.
XSPEC12>response marx_rmf.fits 
Response successfully loaded.
XSPEC12>arf marx_arf.fits 

***XSPEC Error:  data file missing required entries: 
*** Incorrect number of ebins in arf

*** Error processing aux response data - file skipped
XSPEC12>
```

**Comment by DougBurke** [comment]
So, given that XSPEC doesn't like this combination of RMF and ARF, do we want to support it or not?

**Comment by DougBurke** [comment]
@hamogu - I've long lost these data files. I don't suppose you have them (or other similar ones) available?

**Comment by hamogu** [comment]
[marx.zip](https://github.com/sherpa/sherpa/files/5877325/marx.zip)
After grepping through my file system, I found about a dozen directories with files of this name. The first five worked, but then I hit this example which reproduces (with CIAO 4.12) the error above.

**Comment by hamogu** [comment]
[marx_arf.fits.zip](https://github.com/sherpa/sherpa/files/5877405/marx_arf.fits.zip)
I think I forgot the arf file in the previous zip. (Not that the arf is so big that it needs to be zipped, but GH limits what files can be uploaded by file ending, so I might as well zip it.)

**Comment by DougBurke** [comment]
Ta.

**Comment by DougBurke** [comment]
Using just the data in marx.zip (as it has an ARF) I find, with the master branch, the script runs to completion:

```
% md5sum *
2867bf75a619432eb6186fb09be1501a  marx_arf.fits
8d5693fc15f67e4e62d88847c87904b4  marx_pha.fits
e64fe4661d5fa413d5eca0a1aa44b3f8  marx_rmf.fits
```

```
%  cat scp.py
from sherpa.astro.ui import *

load_pha(1, 'marx_pha.fits')
load_rmf(1, 'marx_rmf.fits')
load_arf(1, 'marx_arf.fits')

group_counts(1, 25)
ignore(None, 0.3)
ignore(7, None)


# set source properties
set_source(xsphabs.a * xspowerlaw.p)
a.nH = 1.0
p.PhoIndex = 1.8
p.norm = 0.001

fit(1)
conf(1)
```

```
% python scp.py
...
confidence 1-sigma (68.2689%) bounds:
   Param            Best-Fit  Lower Bound  Upper Bound
   -----            --------  -----------  -----------
   a.nH              1.15401   -0.0820884    0.0858386
   p.PhoIndex        1.96651   -0.0796367    0.0815119
   p.norm         0.00117813 -0.000120068  0.000136078
```

**Comment by hamogu** [comment]
Whatever the change that made it work, great!

**Comment by DougBurke** [comment]
Can you check, since I get the same result with CIAO 4.12 and CIAO 4.13 with these files (ie the fit succeeds). So I don't appear to be triggereing the bug

**Comment by DougBurke** [comment]
I'm going to close this - we can re-open or create a new issue if @hamogu can find another problem case like this.
