### ISSUE TITLE
Can not use XSPEC 12.11.0 (module builds but can not be imported)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#771]
XSPEC 12.11.0 was released March 31 2020. I haven't tried to build it yet, but the changelog looks hopeful that it should at least build (but I've found this chaneglog to miss out important information for those of us who use the model library)

https://heasarc.gsfc.nasa.gov/docs/xanadu/xspec/CHANGELOG.txt

- new models
- changes to the APEC models
- the statistic and "partial" response support shouldn't change our interface, but interesting to see what XSPEC is adding (and we should see if we can get any prototype XRISM responses)

**Comment by DougBurke** [comment]
Looks like they've changed the table-model interface again (or I've done something stupid):

```
% python -c 'from sherpa.astro.xspec import _xspec'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-xspec-12110/sherpa/astro/xspec/__init__.py", line 67, in <module>
    from .utils import ModelMeta, version_at_least, equal_or_greater_than
  File "/home/dburke/sherpa/sherpa-xspec-12110/sherpa/astro/xspec/utils.py", line 21, in <module>
    from . import _xspec
ImportError: /home/dburke/sherpa/sherpa-xspec-12110/sherpa/astro/xspec/_xspec.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z6tabintPfiS_iPKciS1_S_S_
```
