### ISSUE TITLE
RMF with no EBOUNDS extension can not be read in with crates backend

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#773]
This is not a high priority issue (although there's a simple fix)

If I have a RMF with only a MATRIX extension (ie no EBOUNDS) - e.g. using CIAO's `dmlist`

```
% dmlist ~/sherpa/temp/voigt/no-ebounds.rmf blocks

--------------------------------------------------------------------------------
Dataset: /home/dburke/sherpa/temp/voigt/no-ebounds.rmf
--------------------------------------------------------------------------------

     Block Name                          Type         Dimensions
--------------------------------------------------------------------------------
Block    1: PRIMARY                        Null
Block    2: MATRIX                         Table         6 cols x 1070     rows
```

then I can read it in with the astropy backend, but not the crates one.

```
>>> from sherpa.astro import io
>>> io.backend.__name__
>>> io.backend.__name__
'sherpa.astro.io.crates_backend'
>>> io.read_rmf('/home/dburke/sherpa/temp/voigt/no-ebounds.rmf')
Traceback (most recent call last):
  File "/home/dburke/local/ciao-4.12/lib/python3.5/site-packages/pycrates/cratedataset.py", line 143, in _get_base_crate
    return self.__crates[crate-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/local/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/io/__init__.py", line 389, in read_rmf
    data, filename = backend.get_rmf_data(arg)
  File "/home/dburke/local/ciao-4.12/lib/python3.5/site-packages/sherpa-4.12.0-py3.5-linux-x86_64.egg/sherpa/astro/io/crates_backend.py", line 847, in get_rmf_data
    ebounds = rmfdataset.get_crate(3)
  File "/home/dburke/local/ciao-4.12/lib/python3.5/site-packages/pycrates/cratedataset.py", line 158, in get_crate
    basecrate = self._get_base_crate( crate )
  File "/home/dburke/local/ciao-4.12/lib/python3.5/site-packages/pycrates/cratedataset.py", line 145, in _get_base_crate
    raise IndexError("Index out of range")
IndexError: Index out of range
```

but

```
>>> from sherpa.astro import io
>>> io.backend.__name__
'sherpa.astro.io.pyfits_backend'
>>> io.read_rmf('/home/dburke/sherpa/temp/voigt/no-ebounds.rmf')
<DataRMF data set instance '/home/dburke/sherpa/temp/voigt/no-ebounds.rmf'>
```

The problem is that there's no check for an `IndexError` in the IO code - i.e. we should have

```
    if ebounds is None:
        try:
            ebounds = rmfdataset.get_crate(3)
        except IndexError:
            ebounds = None
```

at https://github.com/sherpa/sherpa/blob/master/sherpa/astro/io/crates_backend.py#L846

**Comment by anetasie** [comment]
@DougBurke Did you try fitting the data using the rmf with no EBOUNDS?

**Comment by DougBurke** [comment]
Technically you should be able to fit without the EBOUNDS data, as it's just for visualization. I haven't tried it.

Looking at [OGIP Calibration Memo CAL/GEN/92-002](https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002/cal_gen_92_002.html) and its adendum
[OGIP Calibration Memo CAL/GEN/92-002a ](https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002a/cal_gen_92_002a.html) it looks like the EBOUNDS extension is a required part of the RMF, so an alternative approach would be for both backends to exit if the block is missing.

I note that XSPEC doesn't read a RMF with no EBOUNDS block (the error message you get isn't very informative).

**Comment by DougBurke** [comment]
```
% xspec

                XSPEC version: 12.11.0
        Build Date/Time: Sat Apr  4 09:16:32 2020

XSPEC12>data no-response.pi
Error: cannot read response file no-ebounds.rmf
New filename ( "none" or "/*" to return to the XSPEC prompt):
```

where `no-ebounds.rmf` has no EBOUNDS extension.

**Comment by DougBurke** [comment]
And with the previous release:

```
% xspec

                XSPEC version: 12.10.1m
        Build Date/Time: Fri Sep  6 10:10:09 2019

XSPEC12>data no-response.pi

*** Error processing response data - file skipped

1 spectrum  in use

Spectral Data File: no-response.pi  Spectrum 1
Net count rate (cts/s) for Spectrum:1  1.271e-01 +/- 1.528e-03 (63.0 % total)
 Assigned to Data Group 1 and Plot Group 1
  Noticed Channels:  1-405
  Telescope: CHANDRA Instrument: ACIS  Channel Type: PI
  Exposure Time: 8.9e+04 sec
  Filtering Keys:
    key1: 232
    key2: 232
    key3: 0
    key4: 0
    key5: 358.1
 Using fit statistic: chi
 Using test statistic: chi
 Using Background File                aciss_9_bkg.pi
  Background Exposure Time: 1.077e+06 sec
 No response loaded.

***Warning!  One or more spectra are missing responses,
               and are not suitable for fit.
```

**Comment by anetasie** [comment]
@DougBurke Thanks for checking. I agree, the behavior of the backends should be the same in this case.

**Comment by DougBurke** [comment]
I'm leaning more towards the "require the EBOUNDS block" for RMF files - it would simplify a bunch of code !

**Comment by DougBurke** [comment]
Recent changes mean that both crates and pyfits backend error out with a RMF file with no EBOUNDS block, so closing this:

```
>>> from sherpa.astro.io import pyfits_backend, crates_backend
>>> from sherpa.astro import io
>>> io.backend.name
'pyfits'
>>> io.read_rmf("hack.rmf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/__init__.py", line 620, in read_rmf
    matrixes, ebounds, filename = backend.get_rmf_data(arg)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/pyfits_backend.py", line 818, in get_rmf_data
    ebounds = _read_rmf_ebounds(rmf, filename, "EBOUNDS")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/pyfits_backend.py", line 779, in _read_rmf_ebounds
    ebounds = hdus[blname]
              ~~~~^^^^^^^^
  File "/home/dburke/micromamba/envs/ciaot-no-sherpa/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 390, in __getitem__
    super().__getitem__, self._positive_index_of(key)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/micromamba/envs/ciaot-no-sherpa/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 856, in _positive_index_of
    index = self.index_of(key)
            ^^^^^^^^^^^^^^^^^^
  File "/home/dburke/micromamba/envs/ciaot-no-sherpa/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 838, in index_of
    raise KeyError(f"Extension {key!r} not found.")
KeyError: "Extension 'EBOUNDS' not found."
```

and

```
>>> io.backend = crates_backend
>>> io.backend.name
'crates'
>>> io.read_rmf("hack.rmf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/__init__.py", line 620, in read_rmf
    matrixes, ebounds, filename = backend.get_rmf_data(arg)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/crates_backend.py", line 814, in get_rmf_data
    ebounds = _read_rmf_ebounds(rmfdataset, filename, "EBOUNDS")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dburke/sherpa/sherpa-xspec/sherpa/astro/io/crates_backend.py", line 771, in _read_rmf_ebounds
    raise IOErr(f"Unable to read {blname} from {filename}")
sherpa.utils.err.IOErr: Unable to read EBOUNDS from hack.rmf
>>> 
```
