### ISSUE TITLE
numpy 1.19.0 is out, does not support python 3.5, breaks some things we use, and adds deprecation

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#831]
So, I can't find 1.19 docs easily on the scipy site (e.g. https://numpy.org/doc/stable/ still returns v1.18 for me), but there is https://github.com/numpy/numpy/releases which says

> This NumPy release is marked by the removal of much technical debt:
support for Python 2 has been removed, many deprecations have been
expired, and documentation has been improved. The polishing of the
random module continues apace with bug fixes and better usability from
Cython.
>
> The Python versions supported for this release are 3.6-3.8. Downstream
developers should use Cython >= 0.29.16 for Python 3.8 support and
OpenBLAS >= 3.7 to avoid problems on the Skylake architecture.

# previous notes

numpy 1.19.0 has just made it onto the system we're using, and it loos to break the sphinx doc build on travis.

**EDITED TO ADD** actually, I believe it is more widespread than just the doc build, but also things like `python setup.py develop`

# success from yesterday

https://travis-ci.org/github/sherpa/sherpa/jobs/700406019#L848

uses numpy 1.18.5

# new failure (no significant changes to the docs)

https://travis-ci.org/github/sherpa/sherpa/jobs/700566553#L848

uses numpy 1.19.0, and the error is

```
% $ python setup.py $INSTALL_TYPE
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    from helpers.extensions import static_ext_modules
  File "/home/travis/build/sherpa/sherpa/helpers/__init__.py", line 25, in <module>
    from .sherpa_config import sherpa_config
  File "/home/travis/build/sherpa/sherpa/helpers/sherpa_config.py", line 25, in <module>
    from numpy.distutils.core import Command
ImportError: cannot import name 'Command' from 'numpy.distutils.core' (/home/travis/miniconda/envs/build/lib/python3.7/site-packages/numpy/distutils/core.py)
The command "python setup.py $INSTALL_TYPE" failed and exited with 1 during .
```

**Comment by DougBurke** [comment]
I have a test build at https://github.com/sherpa/sherpa/pull/830/commits/486f883c8150dd0c34989b603ff10c1011019d89 to work around this (by fixing NumPy to 1.18) until we sort this out properly.

**Comment by DougBurke** [comment]
Some things to address:

a) numpy.distutils.core does not export Command

The `numpy.distutils.core` module used to include `from distutils.core import *` and I expect this picked up the `Command` class from `distutils.cmd`.

I assume this is an easy fix, and is hopefully not very version specific.

b) there are now warnings from `to_string` (e.g. the 1D cache code, so pervasive) 

This can be changed to `to_bytes`, which has been around since numpy 1.9.
