### ISSUE TITLE
DataIMG and coord attribute versus set_coord method

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#854]
This is not an issue for the sherpa.astro.ui layer, but for those of us who wan't to use the objects directly.

The `sherpa.astro.data.DataIMG` class provides a `coord` attribute, and it can be set either

- by changing the attribute directly (using @property.set this uses the `_set_coord` method)
- by using the `set_coord` method

I believe that they should be the same, but at present `set_coord` does some extra work and then calls `_set_coord` (which repeats some of the tests it has just done, but that's a minor issue). The trouble is that the `coord` setting is used to control the behavior of some accessors - e.g. what values get returned by `get_indep` - but this is only set up if you call `set_coord`. 

All I think needs to be done is to move the logic from `set_coord` into `_set_coord` and then make `set_coord` just call `_set_coord`. Alternatively there *may* be a reason why we want this separate, but I can't see a good reason why.

# Example

```
import sherpa.astro.io

d1 = sherpa.astro.io.read_image('sherpa-test-data/sherpatest/image2.fits')
d2 = sherpa.astro.io.read_image('sherpa-test-data/sherpatest/image2.fits')

d1.set_coord('physical')
d2.coord = 'physical'

assert d1.coord == d2.coord

d1.notice2d('circle(4050,4250,100)')
d2.notice2d('circle(4050,4250,100)')

y1 = d1.get_y(filter=True)
y2 = d2.get_y(filter=True)

print(len(y1))
print(len(y2))
```

I would expect the two print lines to be the same, but it instead prints

```
7857
0
```

Note that 7857 is the correct value for this dataset/filter, and the difference is because without the extra code that `set_coord` does, the filtering on `d2` doesn't work because the coordinates are all borked (technical term).

**Comment by DougBurke** [comment]
With #1414 merged we now have

```
>>> d2 = io.read_image("sherpa-test-data/sherpatest/image2.fits")
>>> d2.coord = 'physical'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lagado.real/sherpa/sherpa-main/sherpa/utils/__init__.py", line 135, in __setattr__
    object.__setattr__(self, name, val)
AttributeError: property 'coord' of 'DataIMG' object has no setter
```
