### ISSUE TITLE
sherpa.models.model.FilterModel - should we remove it?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#887]
In my recent spelunking I've come across the FilterModel class which has no documentation and is only used in one place - a test to check we can create it. I show below it's use, and the fact that it appears to not work. Since it isn't used anywhere I suggest we remove it.

```
>>> from sherpa.models.basic import Const1D
>>> m = Const1D()
>>> m.c0 = 10
>>> m([1, 2, 3])
array([10., 10., 10.])
>>> m2 = m[2, 4 ,6]
>>> type(m2)
<class 'sherpa.models.model.FilterModel'>
>>> print(m2)
(const1d)[2,4,6]
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   const1d.c0   thawed           10 -3.40282e+38  3.40282e+38
```

So we can create a filter model, but trying to evaluate it raises an error.

```
>>> m2([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/anaconda/envs/ciao412/lib/python3.7/site-packages/sherpa/models/model.py", line 265, in __call__
    return self.calc([p.val for p in self.pars], *args, **kwargs)
  File "/home/dburke/anaconda/envs/ciao412/lib/python3.7/site-packages/sherpa/models/model.py", line 679, in calc
    return self.model.calc(p, *args, **kwargs)[self.filter]
IndexError: too many indices for array
```

**Comment by anetasie** [comment]
@DougBurke just in time for the discussion on code documentation. I just missed it during the meeting.

**Comment by DougBurke** [comment]
It's a really low-priority issue ;-)

**Comment by hamogu** [comment]
I think you missed what this specific model is good for:
https://github.com/sherpa/sherpa/blob/master/sherpa/models/model.py#L546

It's the default `_getitem__` implementation for any ArtithmetricModel. That's not saying that it can't possibly be removed, but that it's part of the machinary on a much deeper level than "only used in a single test".

**Comment by DougBurke** [comment]
Unfortunately the only test that makes use of this functionality is the "existence" test for the model. I changed the `__getitem__` method to raise a NotImplementedError and the only test that failed was the one below. So I claim it's still unused/untested :-)

```
========================================== FAILURES ==========================================
______________________________ test_composite_model.test_filter ______________________________
[gw1] linux -- Python 3.8.5 /home/dburke/anaconda/envs/sherpa-master/bin/python

self = <test_model.test_composite_model testMethod=test_filter>

    def test_filter(self):
>       m = self.s[::2]

sherpa/models/tests/test_model.py:159:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Sin model instance 's'>, filter = slice(None, None, 2)

    def __getitem__(self, filter):
>       raise NotImplementedError
E       NotImplementedError

sherpa/models/model.py:546: NotImplementedError
```

**Comment by DougBurke** [comment]
For reference, the full test is only

```
    def test_filter(self):
        m = self.s[::2]
        self.assertIs(type(m), FilterModel)
        self.assertTrue(numpy.all(m(self.xx) == self.s(self.xx)[::2]))
 ```

[although this test file is the subject of a commit in a recent PT that changes it to pytest style, so I'd appreciate no changes to this file until #888 lands]

**Comment by DougBurke** [comment]
Closed by #2265.
