### ISSUE TITLE
PHA: if channel or counts not numpy array then strange things can happen

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#927]
This was noticed during #922, which adds tests for the behavior shown below. Note that #793, which has just been merged, converts lists to NumPy arrays, but this doesn't work for the DataPHA (for various reasons). The following was done after #793 was merged, which is why there's warnings now from the DataPHA constructors.

- the group routines will return a very odd-looking warning

```
>>> from sherpa.astro.data import DataPHA
>>> pha = DataPHA('example', [1, 2, 3, 4, 5], [1, 2, 3, 1, 1])
/home/dburke/sherpa/sherpa-pr/sherpa/data.py:49: UserWarning: Converting array [1, 2, 3, 1, 1] to numpy array
  warnings.warn("Converting array {} to numpy array".format(array))
>>> pha.group_counts(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-pr/sherpa/astro/data.py", line 1498, in group_counts
    self._dynamic_group(pygroup.grpNumCounts, self.counts, num,
  File "/home/dburke/sherpa/sherpa-pr/sherpa/astro/data.py", line 1338, in _dynamic_group
    self.grouping, self.quality = group_func(*args, **kwargs)
TypeError: grpNumCounts() Could not parse input arguments, please check input for correct type(s)
```

Although DataPHA has claimed it's converted the counts array to a numpy array, this has actually converted the pha.y field,not pha.counts. When the grouping code is run on it it does not support lists (I'd claim that's a bug-let in the group library but that's out-of-band for here), resulting in a strange error.

If I set the counts to a NumPy array then this works:

```
>>> import numpy as np
>>> pha = DataPHA('example', [1, 2, 3, 4, 5], np.asarray([1, 2, 3, 1, 1]))
>>> pha.group_counts(3)
>>>
```

- filtering can get confused

```
>>> pha = DataPHA('example', [1, 2, 3, 4, 5], [1, 2, 3, 1, 1])
>>> pha.ignore()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/sherpa/sherpa-pr/sherpa/data.py", line 796, in ignore
    self.notice(*args, **kwargs)
  File "/home/dburke/sherpa/sherpa-pr/sherpa/astro/data.py", line 2286, in notice
    elo, ehi = self._get_ebins()
  File "/home/dburke/sherpa/sherpa-pr/sherpa/astro/data.py", line 938, in _get_ebins
    elo = self.channel - 0.5
TypeError: unsupported operand type(s) for -: 'list' and 'float'
```

Converting the channel value to a NumPy array fixes this:

```
>>> pha = DataPHA('example', np.asarray([1, 2, 3, 4, 5]), [1, 2, 3, 1, 1])
>>> pha.ignore()
```

The following code fixes this:

```
% git diff sherpa/astro/
diff --git a/sherpa/astro/data.py b/sherpa/astro/data.py
index 01772cb6..d51b2808 100644
--- a/sherpa/astro/data.py
+++ b/sherpa/astro/data.py
@@ -25,9 +25,10 @@ Classes for storing, inspecting, and manipulating astronomical data sets
 import os.path
 import logging
 import warnings
+
 import numpy
-import hashlib

+import sherpa.data
 from sherpa.data import Data1DInt, Data2D, Data, Data2DInt, Data1D, IntegratedDataSpace2D
 from sherpa.models.regrid import EvaluationSpace1D
 from sherpa.utils.err import DataErr, ImportErr
@@ -738,12 +739,17 @@ class DataPHA(Data1D):
     def __init__(self, name, channel, counts, staterror=None, syserror=None,
                  bin_lo=None, bin_hi=None, grouping=None, quality=None,
                  exposure=None, backscal=None, areascal=None, header=None):
+
+        # the error values are checked in the superclass
+        channel = sherpa.data._check(channel)
+        counts = sherpa.data._check(counts)
+
         self.channel = channel
         self.counts = counts
-        self.bin_lo = bin_lo
-        self.bin_hi = bin_hi
-        self.quality = quality
-        self.grouping = grouping
+        self.bin_lo = sherpa.data._check(bin_lo)
+        self.bin_hi = sherpa.data._check(bin_hi)
+        self.quality = sherpa.data._check(quality)
+        self.grouping = sherpa.data._check(grouping)
         self.exposure = exposure
         self.backscal = backscal
         self.areascal = areascal
```

however we then need to fix sherpa/astro/tests/test_astro_data.py test_ungroup and test_unsubtract since they set bin_lo and bin_hi to scalar values when it should be an array. Actually, this is my assumption, I'm not 100% convinced of the bin_lo/hi values.

I haven't made these changes as I'm waiting for #922 to get accepted.

**Comment by hamogu** [comment]
SDS has decided that any input to Dataclasses for x, y, x_lo, x_hi, sys_err, stat_err etc should be converted to numpy arrays in the constructor. People should use numpy arrays anyway and
we've implicitly claimed that the type of input does not matter for the
result, so we are fixing a bug here, not "breaking people's code who
relied on having a different answer when they put in the tuple instead
of a numpy array".

**Comment by hamogu** [comment]
see also #703
